## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""

## @section Common parameters

## @param kubeVersion Override Kubernetes version
##
kubeVersion: ""
## @param nameOverride String to partially override common.names.fullname
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""
## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}

db:
  #host:
  port: 3306
  user: root
  #password:

dbVariables: {}
#  hostVariable:
#  hostPort:
#  hostUser:
#  hostPassword:

image:
  registry: docker.io
  repository: bitnami/mariadb
  tag: 10.6.10-debian-11-r6

databases: []

users: []

job: []
   # extraEnvVars:
   #   - name: FOO
   #     value: "bar"
#  extraEnvVars: []
   ## @param extraEnvVarsCM Name of existing ConfigMap containing extra env vars
   ##
#  extraEnvVarsCM: ""
   ## @param extraEnvVarsSecret Name of existing Secret containing extra env vars
   ##
#  extraEnvVarsSecret: ""
