# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: ldap-manager
      image: https://hub.docker.com/r/vibhuvioio/ldap-manager
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 1.0.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Modern web-based management UI for OpenLDAP, multi-cluster, secure password caching.
home: https://robobee-repos.github.io/helm-charts-charts/
keywords:
- application
- ldap
- web
maintainers:
- name: Erwin Müller
  url: https://github.com/robobee-repos/helm-charts-charts
name: ldap-manager
sources:
- https://vibhuvioio.com/ldap-manager/
version: 1.0.3
