ingresses:
  - ingressClassName: "nginx"
    hostname: test.aaaa.de
    extraTls:
    - hosts:
        - test.aaaa.de
      secretName: test.aaaa.de-tls
  - ingressClassName: "nginx"
    hostname: foo.aaaa.de
    annotations:
      nginx.ingress.kubernetes.io/permanent-redirect: https://test.aaa.de
    extraTls:
    - hosts:
        - foo.aaaa.de
      secretName: test.aaaa.de-tls
