## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""

## @section Common parameters

## @param kubeVersion Override Kubernetes version
##
kubeVersion: ""
## @param nameOverride String to partially override common.names.fullname
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""
## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}

jobs: []
    ## Job name
#  - name:
    ## Job image
    ## ref: https://hub.docker.com/r/bitnami/redmine/tags/
    ## @param image.registry Job image registry
    ## @param image.repository Job image repository
    ## @param image.tag Job image tag (immutable tags are recommended)
    ## @param image.pullPolicy Job image pull policy
    ## @param image.pullSecrets [array] Job image pull secrets
    ## @param image.debug Enable image debug mode
    ##
#    image:
    #registry: docker.io
    #repository: bitnami/redmine
    #tag: 4.2.3-debian-10-r128
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
#    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ##
    # pullSecrets:
    #   - myRegistryKeySecretName
#    pullSecrets: []
    ## Enable debug mode
    ##
#    debug: false
    ## @param command Override default container command (useful when using custom images)
    ##
#    command: []
    ## @param args Override default container args (useful when using custom images)
    ##
#    args: []
    ## @param extraEnvVars Array with extra environment variables to add to the Job container
    ## e.g:
    ##
    # extraEnvVars:
    #   - name: FOO
    #     value: "bar"
#    extraEnvVars: []
    ## @param extraEnvVarsCM Name of existing ConfigMap containing extra env vars
    ##
#    extraEnvVarsCM: ""
    ## @param extraEnvVarsSecret Name of existing Secret containing extra env vars
    ##
#    extraEnvVarsSecret: ""

    ## @param schedulerName Alternate scheduler
    ## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
    ##
#    schedulerName: ""
    ## @param serviceAccount.create Specifies whether a ServiceAccount should be created
    ## @param serviceAccount.name The name of the ServiceAccount to create. Defaults to the `redmine.fullname` macro
    ##
#    serviceAccount:
#      create: false
#      name: ""
    ## @param hostAliases [array] Job pod host aliases
    ## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
    ##
#    hostAliases: []
    ## @param restartPolicy
    ##
#    restartPolicy: OnFailure

    ## @param extraVolumes Optionally specify extra list of additional volumes for Job pods
    ##
#    extraVolumes: []
    ## @param extraVolumeMounts Optionally specify extra list of additional volumeMounts for Job container(s)
    ##
#    extraVolumeMounts: []

    ## @param affinity Affinity for pod assignment
    ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
    ##
#    affinity: {}
    ## @param nodeSelector Node labels for pod assignment
    ## ref: https://kubernetes.io/docs/user-guide/node-selection/
    ##
#    nodeSelector: {}
    ## @param tolerations Tolerations for pod assignment
    ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
    ##
#    tolerations: []
    ## Job containers' resource requests and limits
    ## ref: https://kubernetes.io/docs/user-guide/compute-resources/
    ## @param resources.limits The resources limits for the Job container
    ## @param resources.requests [object] The requested resources for the Job container
    ##
#    resources:
#      limits: {}
#      requests: {}
    ## Configure Pods Security Context
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
    ## @param podSecurityContext.enabled Enabled Job pods' Security Context
    ## @param podSecurityContext.fsGroup Set Job pod's Security Context fsGroup
    ##
#    podSecurityContext:
#      enabled: false
#      fsGroup: 1001
    ## Configure Container Security Context (only main container)
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
    ## @param containerSecurityContext.enabled Enabled Job containers' Security Context
    ## @param containerSecurityContext.runAsUser Set Job container's Security Context runAsUser
    ##
#    containerSecurityContext:
#      enabled: false
#      runAsUser: 1001

configMaps: []
#  - name: jenkins-cas
#    data:
#      jenkins.yaml: |-
#        clouds:

secrets: []
#  - name: jenkins-cas
#    type: Opaque
#    data:
#      jenkins.yaml: |-
#        clouds:

pvcs: []
#  - name: jenkins-cas
#    type: Opaque
#    data:
#      jenkins.yaml: |-
#        clouds:

ingressesDefaults:
  pathType: ImplementationSpecific
  apiVersion: ""
  ingressClassName: ""
  path: /
  annotations: {}
  tls: false
  selfSigned: false
  extraHosts: []
  extraTls: []
  secrets: []

ingresses: []
#  - ingress:
#    ## @param ingress.enabled Enable ingress record generation for WordPress
#    ##
#    enabled: false
#    ## @param ingress.pathType Ingress path type
#    ##
#    pathType: ImplementationSpecific
#    ## @param ingress.apiVersion Force Ingress API version (automatically detected if not set)
#    ##
#    apiVersion: ""
#    ## @param ingress.ingressClassName IngressClass that will be be used to implement the Ingress (Kubernetes 1.18+)
#    ## This is supported in Kubernetes 1.18+ and required if you have more than one IngressClass marked as the default for your cluster .
#    ## ref: https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/
#    ##
#    ingressClassName: ""
#    ## @param ingress.hostname Default host for the ingress record
#    ##
#    hostname: wordpress.local
#    ## @param ingress.path Default path for the ingress record
#    ## NOTE: You may need to set this to '/*' in order to use this with ALB ingress controllers
#    ##
#    path: /
#    ## @param ingress.annotations Additional annotations for the Ingress resource. To enable certificate autogeneration, place here your cert-manager annotations.
#    ## For a full list of possible ingress annotations, please see
#    ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
#    ## Use this parameter to set the required annotations for cert-manager, see
#    ## ref: https://cert-manager.io/docs/usage/ingress/#supported-annotations
#    ##
#    ## e.g:
#    ## annotations:
#    ##   kubernetes.io/ingress.class: nginx
#    ##   cert-manager.io/cluster-issuer: cluster-issuer-name
#    ##
#    annotations: {}
#    ## @param ingress.tls Enable TLS configuration for the host defined at `ingress.hostname` parameter
#    ## TLS certificates will be retrieved from a TLS secret with name: `{{- printf "%s-tls" .Values.ingress.hostname }}`
#    ## You can:
#    ##   - Use the `ingress.secrets` parameter to create this TLS secret
#    ##   - Relay on cert-manager to create it by setting the corresponding annotations
#    ##   - Relay on Helm to create self-signed certificates by setting `ingress.selfSigned=true`
#    ##
#    tls: false
#    ## @param ingress.selfSigned Create a TLS secret for this ingress record using self-signed certificates generated by Helm
#    ##
#    selfSigned: false
#    ## @param ingress.extraHosts An array with additional hostname(s) to be covered with the ingress record
#    ## e.g:
#    ## extraHosts:
#    ##   - name: wordpress.local
#    ##     path: /
#    ##
#    extraHosts: []
#    ## @param ingress.extraPaths An array with additional arbitrary paths that may need to be added to the ingress under the main host
#    ## e.g:
#    ## extraPaths:
#    ## - path: /*
#    ##   backend:
#    ##     serviceName: ssl-redirect
#    ##     servicePort: use-annotation
#    ##
#    extraPaths: []
#    ## @param ingress.extraTls TLS configuration for additional hostname(s) to be covered with this ingress record
#    ## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
#    ## e.g:
#    ## extraTls:
#    ## - hosts:
#    ##     - wordpress.local
#    ##   secretName: wordpress.local-tls
#    ##
#    extraTls: []
#    ## @param ingress.secrets Custom TLS certificates as secrets
#    ## NOTE: 'key' and 'certificate' are expected in PEM format
#    ## NOTE: 'name' should line up with a 'secretName' set further up
#    ## If it is not set and you're using cert-manager, this is unneeded, as it will create a secret for you with valid certificates
#    ## If it is not set and you're NOT using cert-manager either, self-signed certificates will be created valid for 365 days
#    ## It is also possible to create and manage the certificates outside of this helm chart
#    ## Please see README.md for more information
#    ## e.g:
#    ## secrets:
#    ##   - name: wordpress.local-tls
#    ##     key: |-
#    ##       -----BEGIN RSA PRIVATE KEY-----
#    ##       ...
#    ##       -----END RSA PRIVATE KEY-----
#    ##     certificate: |-
#    ##       -----BEGIN CERTIFICATE-----
#    ##       ...
#    ##       -----END CERTIFICATE-----
#    ##
#    secrets: []
