# templates/namespace-rbac.yaml
{{- if .Values.rbac.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.names.fullname" . }}-deployer
  namespace: {{ include "myapp.namespaceName" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "common.names.fullname" . }}-deployer
  namespace: {{ include "myapp.namespaceName" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
rules:
{{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.names.fullname" . }}-deployer
  namespace: {{ include "myapp.namespaceName" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "common.names.fullname" . }}-deployer
subjects:
- kind: ServiceAccount
  name: {{ include "common.names.fullname" . }}-deployer
  namespace: {{ include "myapp.namespaceName" . }}
{{- end }}
