{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{ if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openldap.secretName" . }}
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.extraLabels }}
  {{ toYaml .Values.extraLabels | indent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  OPENLDAP_BOOTSTRAP_CONFIG_ROOT_PASSWORD_HASHED: {{ .Values.passwordsSecrets.OPENLDAP_BOOTSTRAP_CONFIG_ROOT_PASSWORD_HASHED | b64enc | quote }}
  OPENLDAP_BOOTSTRAP_DATA_ROOT_PASSWORD_HASHED: {{ .Values.passwordsSecrets.OPENLDAP_BOOTSTRAP_DATA_ROOT_PASSWORD_HASHED | b64enc | quote }}
  OPENLDAP_BOOTSTRAP_DATA_READONLY_PASSWORD_HASHED: {{ .Values.passwordsSecrets.OPENLDAP_BOOTSTRAP_DATA_READONLY_PASSWORD_HASHED | b64enc | quote }}
  OPENLDAP_BOOTSTRAP_MONITOR_READONLY_PASSWORD_HASHED: {{ .Values.passwordsSecrets.OPENLDAP_BOOTSTRAP_MONITOR_READONLY_PASSWORD_HASHED | b64enc | quote }}
{{ end }}
