{{- $serviceAnnotations := .Values.service.annotations -}}
{{- $serviceType := .Values.service.type -}}
{{- $serviceLoadBalancerIP := .Values.service.loadBalancerIP -}}
{{- $serviceLoadBalancerSourceRanges := .Values.service.loadBalancerSourceRanges -}}
{{- $serviceClusterIP := .Values.service.clusterIP -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  annotations:
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if $serviceAnnotations }}
  {{- include "common.tplvalues.render" (dict "value" $serviceAnnotations "context" $) | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ $serviceType }}
  {{- if and $serviceLoadBalancerIP (eq $serviceType "LoadBalancer") }}
  loadBalancerIP: {{ $serviceLoadBalancerIP }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq $serviceType "LoadBalancer") $serviceLoadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- include "common.tplvalues.render" (dict "value" $serviceLoadBalancerSourceRanges "context" $) | nindent 4 }}
  {{- end }}
  {{- if and (eq $serviceType "ClusterIP") $serviceClusterIP }}
  clusterIP: {{ $serviceClusterIP }}
  {{- end }}
  ports:
    - name: ldap
      port: {{ .Values.service.ports.ldap }}
      targetPort: ldap
      {{- if .Values.service.nodePorts.ldap }}
      nodePort: {{ .Values.service.nodePorts.ldap }}
      {{- end }}
    - name: ssl-ldap
      port: {{ .Values.service.ports.sslLdap }}
      targetPort: ssl-ldap
      {{- if .Values.service.nodePorts.sslLdap }}
      nodePort: {{ .Values.service.nodePorts.sslLdap }}
      {{- end }}
  selector:
  {{- include "common.labels.matchLabels" . | nindent 4 }}
