annotations:
  category: iam
apiVersion: v2
appVersion: 2.6.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.x.x
  - name: ltb-passwd
    version: 0.1.x
    condition: ltb-passwd.enabled
  - name: phpldapadmin
    version: 0.1.3
    condition: phpldapadmin.enabled
description: Community developed LDAP software
engine: gotpl
home: https://github.com/robobee-repos/helm-charts/
keywords:
  - ldap
  - openldap
  - iam-stack
maintainers:
  - email: erwin@muellerpublic.de
    name: Erwin Müller
name: openldap
sources:
  - https://github.com/robobee-repos/helm-charts/
version: 1.0.25
