annotations:
  category: iam
apiVersion: v2
appVersion: 1.8.1
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.x.x
description: Community developed self-service-password software
engine: gotpl
home: https://github.com/robobee-repos/helm-charts/
keywords:
  - ldap
  - openldap
  - iam-stack
  - self-service-password
maintainers:
  - email: erwin@muellerpublic.de
    name: Erwin Müller
name: self-service-password
sources:
  - https://github.com/robobee-repos/helm-charts/
version: 1.0.0
