defaultsAcmeStaging:
  name: letsencrypt-staging
  server: https://acme-staging-v02.api.letsencrypt.org/directory
  solvers:
  - http01:
      ingress:
        class: nginx

defaultsAcmeProd:
  name: letsencrypt-production
  server: https://acme-v02.api.letsencrypt.org/directory
  solvers:
  - http01:
      ingress:
        class: nginx

#acmeStagingIssuers:
#- name: letsencrypt-staging
#  email: erwin@muellerpublic.de
#acmeProdIssuers:
#- email: erwin@muellerpublic.de
