annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 2.5.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: HAProxy is a TCP proxy and a HTTP reverse proxy. It supports SSL termination and offloading, TCP and HTTP normalization, traffic regulation, caching and protection against DDoS attacks.
engine: gotpl
home: https://www.haproxy.org/
keywords:
  - haproxy
  - proxy
  - infrastructure
  - robobee
maintainers:
  - email: erwin@muellerpublic.de
    name: Erwin Müller
name: haproxy
sources:
  - https://github.com/robobee-repos/helm-charts
  - https://hub.docker.com/_/haproxy
  - https://github.com/haproxytech/haproxy
version: 1.0.4
