---
# Source: haproxy/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy
  namespace: "default"
  labels:
    app.kubernetes.io/name: haproxy
    helm.sh/chart: haproxy-0.2.21-robobee-1.0.0
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: haproxy
data:
  haproxy.cfg: |
    global
      log stdout format raw local0
      maxconn 1024
    defaults
      log global
      timeout client 60s
      timeout connect 60s
      timeout server 60s
    frontend fe_main
      bind :8080
      default_backend be_main
    backend be_main
      server web1 10.0.0.1:8080 check
