---
# Source: haproxy/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  namespace: "default"
  labels:
    app.kubernetes.io/name: haproxy
    helm.sh/chart: haproxy-0.2.21-robobee-1.0.0
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: haproxy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: haproxy
      app.kubernetes.io/instance: haproxy
      app.kubernetes.io/component: haproxy
  template:
    metadata:
      annotations:
        checksum/configmap: f730c5b5846b7c889a4de29c786cc6b3bcbfbfb659b7dbb75ef887367bb57f77
      labels:
        app.kubernetes.io/name: haproxy
        helm.sh/chart: haproxy-0.2.21-robobee-1.0.0
        app.kubernetes.io/instance: haproxy
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: haproxy
    spec:
      serviceAccountName: haproxy-foo
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: haproxy
                    app.kubernetes.io/instance: haproxy
                    app.kubernetes.io/component: haproxy
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
      containers:
        - name: haproxy
          image: docker.io/bitnami/haproxy:2.5.0-debian-10-r22
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1001
          ports:
            - containerPort: 8080
              name: http
          env:
          envFrom:
          resources:
            limits: {}
            requests: {}
          livenessProbe:
            # Using exec instead of tcpSocket to avoid noise in te logs
            exec:
              command:
                - pgrep
                - haproxy
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            # Using exec instead of tcpSocket to avoid noise in te logs
            exec:
              command:
                - pgrep
                - haproxy
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          volumeMounts:
            - name: haproxy-conf
              mountPath: /bitnami/haproxy/conf
      volumes:
        - name: haproxy-conf
          configMap:
            name: haproxy
