---
# Source: haproxy/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: certs-haproxy-foo
  namespace: "kube-certs"
  labels:
    app.kubernetes.io/name: haproxy
    helm.sh/chart: haproxy-1.0.8
    app.kubernetes.io/instance: certs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: haproxy
