---
# Source: haproxy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: "default"
  labels:
    app.kubernetes.io/name: haproxy
    helm.sh/chart: haproxy-1.0.2
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: haproxy
  annotations:
spec:
  type: NodePort
  externalTrafficPolicy: "Cluster"
  loadBalancerSourceRanges: []
  
  externalIPs:
  - 46.19.33.244
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  - name: https
    protocol: TCP
    port: 443
    targetPort: https
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: ssh
  selector:
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/component: haproxy
