---
# Source: haproxy/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: haproxy-foo
  namespace: "default"
  labels:
    app.kubernetes.io/name: haproxy
    helm.sh/chart: haproxy-1.0.0
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: haproxy
