{{- if .Values.backendTLSPolicy.enabled }}
{{- $fullName := include "common.names.fullname" . }}
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: {{ .Values.backendTLSPolicy.name | default $fullName }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.backendTLSPolicy.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.backendTLSPolicy.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  targetRefs:
  {{- range .Values.backendTLSPolicy.targetRefs }}
    - group: {{ .group | quote }}
      kind: {{ .kind }}
      name: {{ .name }}
      {{- if .sectionName }}
      sectionName: {{ .sectionName }}
      {{- end }}
  {{- end }}
  {{- if .Values.backendTLSPolicy.validation.enabled }}
  validation:
    {{- if .Values.backendTLSPolicy.validation.caCertificateRefs }}
    caCertificateRefs:
      group: {{ .Values.backendTLSPolicy.validation.caCertificateRefs.group | quote }}
      kind: {{ .Values.backendTLSPolicy.validation.caCertificateRefs.kind }}
      name: {{ .Values.backendTLSPolicy.validation.caCertificateRefs.name }}
    {{- end }}
    hostname: {{ .Values.backendTLSPolicy.validation.hostname }}
    {{- if .Values.backendTLSPolicy.validation.subjectAltNames }}
    subjectAltNames: {{ .Values.backendTLSPolicy.validation.subjectAltNames }}
    {{- end }}
  {{- end }}
{{- end }}
