(function(g){var window=this;'use strict';var xX7=async function(b,C,F){b.D=g.sN(C,F)},VZ=function(b){b.isActive()||b.start()},XST=function(b,C){var F=new g.es;
F.languageCode=b.languageCode;F.languageName=b.languageName;F.name=b.name;F.displayName=b.displayName;F.kind=b.kind;F.isDefault=!1;F.O=b.O;F.isTranslateable=b.isTranslateable;F.vssId=b.vssId;F.url=b.url;F.translationLanguage=C;b.xtags&&(F.xtags=b.xtags);b.captionId&&(F.captionId=b.captionId);return F},gE=function(b,C){return C?b.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},WB5=function(b){return g.FH(b)||b.C("web_enable_caption_language_preference_stickiness")},e8k=async function(b,C){b=
b+"|"+C;
C=await g.Wx();if(!C)throw g.n2("gct");return(await g.W1(C)).get("captions",b)},UXs=function(b,C,F){e8k(b,C).then(z=>{z&&F(z.trackData,new g.es(z.metadata))})},Kv=function(b){if(!R87.test(b))throw Error("'"+b+"' is not a valid hex color");
b.length==4&&(b=b.replace(v$T,"#$1$1$2$2$3$3"));b=b.toLowerCase();b=parseInt(b.slice(1),16);return[b>>16,b>>8&255,b&255]},A65=function(){var b={},C="suggest_correction"in g.lo?g.lo.suggest_correction:"Edit caption";
C=C||"";for(let F in b){let z=()=>String(b[F]);
C=C.replace(new RegExp("\\$\\{"+F+"\\}","gi"),z);C=C.replace(new RegExp("\\$"+F,"gi"),z)}return C},Dz=function(){return g.oj("yt-player-caption-display-settings")},J6U=function(b,C){var F=g.Dl(b.segments,C);
F>=0||F<0&&(-F-1)%2===1||(F=-F-1,F>0&&C-b.segments[F-1]===1&&F<b.segments.length&&b.segments[F]-C===1?(g.FT(b.segments,F),g.FT(b.segments,F-1)):F>0&&C-b.segments[F-1]===1?b.segments[F-1]=C:F<b.segments.length&&b.segments[F]-C===1?b.segments[F]=C:(g.V5(b.segments,F,0,C),g.V5(b.segments,F+1,0,C)))},mX3=function(b){return b.O&&b.O.G?b.O.G+b.player.LX()<b.player.getCurrentTime():!1},SyU=function(b,C){if(b.policy.Bj&&b.player.ub()){var F=g.Pc(C,b.policy,{});
F.set("pot",b.player.ub());F=F.DZ()}else F=g.Pc(C,b.policy,{}).DZ();var z={format:"RAW",withCredentials:!0};if(b.policy.XS){z.method="POST";let H=C.N;H&&Object.keys(H).length>0?z.postBody=g.yK(H,g.tA):z.postBody=(0,g.Ov)([120,0])}b.G&&(z.responseType="arraybuffer");var N=++b.AA,h=(0,g.u)();b.D=g.$a(F,z,3,100,-1,H=>{H.errorCode==="net.timeout"&&b.player.FS("capnt",{rn:N++})}).then(H=>{if(b.policy.a8&&N%100===1){var c=(0,g.u)();
b.player.FS("caprsp",{rn:N,ms:c-h,kb:(H.xhr.responseText.length/1024).toFixed()})}a:{H=H.xhr;b.gI();if(b.A){var r=!(b.G?H.response:H.responseText)||H.status>=400;if(c=g.XMD(H)){H=g.Pc(b.A,b.policy,{});b.A.Ay(H,c);SyU(b,b.A);break a}r?b.player.FS("capfail",{status:H.status}):(g.QY("fcb_r",(0,g.u)(),b.player.getVideoData()?.zy||""),c=b.A.uB[0],r=c.vv,b.B!=null&&b.Z!==r&&(b.G?b.B(H.response,(c.segmentStartTime+b.player.LX())*1E3):b.B(H.responseText,(c.segmentStartTime+b.player.LX())*1E3),b.Z=r))}b.A=
null;b.D=null}}).YS(H=>{b.A=null;
b.D=null;b.player.FS("capfail",{rn:N,status:H.xhr?.status})});
b.A=C;J6U(b.N,b.A.uB[0].vv)},atb=function(b,C){return C!=null&&C in b.D.O?b.D.O[C]:null},upB=function(b,C,F){var z=[];
for(let N in b.D.O){if(!b.D.O.hasOwnProperty(N))continue;let h=b.D.O[N];if(g.FW(h,F||null)){let H=h.info.captionTrack;H&&H.languageCode===C&&z.push(h)}}return z.length?z[0]:null},ZWn=function(b,C){var F=[];
for(let N in b.D.O){if(!b.D.O.hasOwnProperty(N))continue;var z=b.D.O[N];if(g.FW(z,C||null)){let h=z.info.id,H=h,c=`.${h}`,r="",L="";if(z=z.info.captionTrack)h=z.languageCode,H=z.displayName,c=z.vssId,r=z.kind,L=z.id;F.push(new g.es({id:N,languageCode:h,languageName:H,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:c,kind:r,captionId:L}))}}return F},wSV=function(b,C,F,z){var N=C/360*16;
C>=b&&(b=640,z>F*1.3&&(b=480),N=F/b*16);return N},E$O=function(b){var C=1+.25*(b.fontSizeIncrement||0);
if(b.offset===0||b.offset===2)C*=.8;return C},tqb=function(b,C){var F="vertical-rl";
b.O.Mi===1&&(F="vertical-lr");g.Ow&&(F=F==="vertical-lr"?"tb-lr":"tb-rl");g.xO(C,"-o-writing-mode",F);g.xO(C,"-webkit-writing-mode",F);g.xO(C,"writing-mode",F);g.xO(C,"text-orientation","upright");g.jQ(C,"ytp-vertical-caption");b.D.params.Gi===3&&(g.xO(C,"text-orientation",""),g.xO(C,"transform","rotate(180deg)"))},Ity=function(b,C){var F={},z=C.background?C.background:b.O.JM.background;
if(C.backgroundOpacity!=null||C.background){var N=C.backgroundOpacity!=null?C.backgroundOpacity:b.O.JM.backgroundOpacity;z=Kv(z);F.background="rgba("+z[0]+","+z[1]+","+z[2]+","+N+")";b.LJ&&(F["box-decoration-break"]="clone",F["border-radius"]=`${b.Et*.25}px`)}if(C.fontSizeIncrement!=null||C.offset!=null)F["font-size"]=`${b.xf*E$O(C)}px`;b.experiments.Yf("enable_player_captions_new_style_defaults")&&(F["line-height"]="1.375");z=1;N=C.color||b.O.JM.color;if(C.color||C.textOpacity!=null)N=Kv(N),z=C.textOpacity==
null?b.O.JM.textOpacity:C.textOpacity,N="rgba("+N[0]+","+N[1]+","+N[2]+","+z+")",F.color=N,F.fill=N;var h=C.charEdgeStyle;h===0&&(h=void 0);if(h){N=`rgba(34, 34, 34, ${z})`;let r=`rgba(204, 204, 204, ${z})`;C.tX&&(r=N=C.tX);let L=b.xf/16/2,K=Math.max(L,1);var H=Math.max(2*L,1),c=Math.max(3*L,1);let D=Math.max(5*L,1);z=[];switch(h){case 4:for(;c<=D;c+=L)z.push(`${H}px ${H}px ${c}px ${N}`);break;case 1:H=window.devicePixelRatio>=2?.5:1;for(h=K;h<=c;h+=H)z.push(`${h}px ${h}px ${N}`);break;case 2:z.push(`${K}px ${K}px ${r}`);
z.push(`-${K}px -${K}px ${N}`);break;case 3:for(c=0;c<5;c++)z.push(`0 0 ${H}px ${N}`)}F["text-shadow"]=z.join(", ")}N="";switch(C.fontFamily){case 1:N='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:N='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:N='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:N='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:N='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:N=g.u9()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:N='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}N&&(F["font-family"]=N);N=C.offset;N==null&&(N=b.O.JM.offset);switch(N){case 0:F["vertical-align"]="sub";break;case 2:F["vertical-align"]="super"}C.fontFamily===7&&(F["font-variant"]="small-caps");C.bold&&(F["font-weight"]="bold");C.italic&&(F["font-style"]="italic");C.underline&&
(F["text-decoration"]="underline");C.P0&&(F.visibility="hidden");C.a5===1&&b.N&&(F["text-combine-upright"]="all",F["text-orientation"]="mixed",N=g.r$||g.cx,b.D.params.Gi===3?F.transform=N?"rotate(90deg)":"rotate(180deg)":N&&(F.transform="rotate(-90deg)"));if(C.textEmphasis===1||C.textEmphasis===2||C.textEmphasis===3||C.textEmphasis===4||C.textEmphasis===5)if(g.r$)F["font-weight"]="bold";else switch(F["text-emphasis-style"]="filled circle",F["text-emphasis-color"]="currentcolor",F["webkit-text-emphasis"]=
"filled circle",C.textEmphasis){case 4:case 3:F["text-emphasis-position"]="under left";F["webkit-text-emphasis-position"]="under left";break;case 5:case 2:F["text-emphasis-position"]="over right",F["webkit-text-emphasis-position"]="over right"}return F},GLb=function(b,C){if(b.Hv&&C.length===0)return 0;
b=1;for(let F=0;F<C.length;F++){let z=C[F];typeof z.text==="string"&&(b+=z.text.split("\n").length-1,z.append||F===0||b++)}return b},M4=function(b){b=b.split("px");
return b.length>0?(b=Number(b[0]))?b:0:0},CG3=function(b,C,F){b.XS=b.XS||!!F;
var z={};Object.assign(z,b.O.JM);Object.assign(z,F||C.O);Object.assign(z,b.h8.JM);(F=!b.G)&&Qt3(b);var N=b.ZQ&&b.KJ&&g.mn(z,b.KJ)?b.ZQ:bF5(b,z),h=typeof C.text==="string",H=h?C.text.split("\n"):[C.text];for(let r=0;r<H.length;r++){var c=r>0||!C.append;let L=H[r];c&&!F?(Qt3(b),N=bF5(b,z)):c&&F&&(F=!1);L&&(N.appendChild(h?g.h8(L):L),h||L.tagName!=="RUBY"||L.childElementCount!==4||g.r$||!g.U9(L.children[2],"text-emphasis")||(c=b.N?"padding-right":"padding-top",g.U9(L.children[2],"text-emphasis-position")&&
(c=b.N?"padding-left":"padding-bottom"),g.QL?g.xO(N,c,"1em"):g.xO(N,c,"0.5em")))}b.KJ=z;b.ZQ=N;b.K.push(C)},Qt3=function(b){if(b.G){var C=b.G;
if(b.LJ){var F=b.O.textAlign;F===0?(C=C.firstElementChild)&&g.xO(C,{"border-bottom-left-radius":"0"}):F===1&&(C=C.lastElementChild)&&g.xO(C,{"border-bottom-right-radius":"0"})}}b.G=g.Nv("SPAN");g.xO(b.G,{display:"block"});g.jQ(b.G,"caption-visual-line");b.A.appendChild(b.G)},bF5=function(b,C){var F=g.Nv("SPAN");
g.xO(F,{display:"inline-block","white-space":"pre-wrap"});g.xO(F,Ity(b,C));F.classList.add("ytp-caption-segment");b.G.appendChild(F);b.LJ&&b.A.children.length>1&&(b=b.O.textAlign,b===0?F.previousElementSibling||g.xO(F,{"border-top-left-radius":"0"}):b===1&&g.xO(F,{"border-top-right-radius":"0"}));F.previousElementSibling&&(g.xO(F.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.xO(F,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return F},
zmU=function(b,C,F){if(b===255&&C===255||!b&&!C)return{I1:b,
TM:C,result:0};b=Fos[b];C=Fos[C];if(b&128){var z;if(z=!(C&128))z=C,z=F.ww()&&F.TM===z;if(z)return{I1:b,TM:C,result:1}}else if(C&128&&1<=b&&b<=31)return{I1:b,TM:C,result:2};return{I1:b,TM:C,result:3}},hmn=function(b,C,F,z){C===255&&F===255||!C&&!F?(++b.A===45&&b.reset(),b.N.D.clear(),b.G.D.clear()):(b.A=0,Nu7(b.N,C,F,z))},HFs=function(b,C){b.O.sort((F,z)=>{var N=F.time-z.time;
return N===0?F.order-z.order:N});
for(let F of b.O)b.time=F.time,F.type===0?hmn(b,F.rA,F.UL,C):F.type===1&&b.D&496&&Nu7(b.G,F.rA,F.UL,C);b.O.length=0},n55=function(b,C){switch(b){case 0:return cQT[(C&127)-32];
case 1:return rQV[C&15];case 2:return Lon[C&31];case 3:return YRk[C&31]}return 0},pv=function(b,C){if(b.style.type===3){var F=0,z=0,N=b.G.time+0,h="",H="",c=N;
for(var r=1;r<=15;++r){var L=!1;for(var K=z?z:1;K<=32;++K){var D=b.A[r][K];if(D.O!==0){F===0&&(F=r,z=K);L=String.fromCharCode(D.O);var P=D.timestamp;P<N&&(N=P);D.timestamp=c;H&&(h+=H,H="");h+=L;L=!0}if((D.O===0||K===32)&&L){H="\n";break}else if(z&&!L)break}if(F&&!L)break}h&&C.N(F,z,N,c,h)}else for(z=F=0,h=N=b.G.time+0,H=1;H<=15;++H)for(c="",r=1;r<=32;++r)if(K=b.A[H][r],D=K.O,D!==0&&(F===0&&(F=H,z=r),L=String.fromCharCode(D),P=K.timestamp,P<=N&&(N=P),c+=L,K.reset()),r===32||D===0)c&&C.N(F,z,N,h,c),
N=h,c="",z=F=0},dE=function(b){return b.A[b.row][b.D]},PH=function(b,C,F){C>=2&&b.D>1&&(--b.D,dE(b).O=0);
var z=dE(b);z.timestamp=b.G.time+0;z.O=n55(C,F);b.D<32&&b.D++},V4y=function(b,C,F,z){for(let H=0;H<z;H++)for(let c=0;c<=32;c++){var N=b.A[C+H][c],h=b.A[F+H][c];
N.O=h.O;N.timestamp=h.timestamp}},q4=function(b,C,F){for(let z=0;z<F;z++)for(let N=0;N<=32;N++)b.A[C+z][N].reset()},s3=function(b){b.row=b.O>0?b.O:1;
b.D=1;q4(b,0,15)},g5T=function(b){b.style.set(1);
b.O=b.N;b.O.O=0;b.O.style=b.style;b.A.mode=1<<b.O.N},BH=function(b,C,F){var z=b.D,N=!1;
switch(b.style.get()){case 4:case 1:case 2:b.style.get()===4&&z.O>0||(pv(z,F),s3(b.D),s3(b.N),z.row=15,z.O=C,N=!0)}b.style.set(3);b.O=z;b.O.style=b.style;b.A.mode=1<<z.N;N?z.D=1:z.O!==C&&(z.O>C?(pv(z,F),q4(z,z.row-z.O,C)):z.row<C&&(C=z.O),z.O=C)},KoV=function(b){b.style.set(4);
b.O=b.text;b.O.style=b.style;b.A.mode=1<<b.O.N},Nu7=function(b,C,F,z){b.D.update();
C=zmU(C,F,b.D);switch(C.result){case 0:return;case 1:case 2:return}var N=C.I1;C=C.TM;if(32<=N||!N)b.O.mode&b.O.D&&(F=N,F&128&&(F=127),C&128&&(C=127),b=b.N.O,F&96&&PH(b,0,F),C&96&&PH(b,0,C),F!==0&&C!==0&&b.style.type===3&&pv(b,z));else if(N&16)a:if(!b.D.matches(N,C)&&(F=b.D,F.I1=N,F.TM=C,F.state=2,F=N&8?b.Z:b.A,b.N=F,b.O.mode=1<<(b.G<<2)+(F.G<<1)+(F.style.type===4?1:0),(b.O.mode|1<<(b.G<<2)+(F.G<<1)+(F.style.type!==4?1:0))&b.O.D))if(C&64){z=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(N&7)<<1|C>>5&1];
b=C&16?((C&14)>>1)*4:0;C=F.O;switch(F.style.get()){case 4:z=C.row;break;case 3:if(z!==C.row){if(z<C.O&&(z=C.O,z===C.row))break;var h=1+C.row-C.O;let H=1+z-C.O;V4y(C,H,h,C.O);F=h;N=C.O;H<h?(h=H+N-h,h>0&&(F+=h,N-=h)):(h=h+N-H,h>0&&(N-=h));q4(C,F,N)}}C.row=z;C.D=b+1}else switch(N&7){case 1:switch(C&112){case 32:PH(F.O,0,32);break a;case 48:C===57?(z=F.O,dE(z).O=0,z.D<32&&z.D++):PH(F.O,1,C&15)}break;case 2:C&32&&PH(F.O,2,C&31);break;case 3:C&32&&PH(F.O,3,C&31);break;case 4:case 5:if(32<=C&&C<=47)switch(C){case 32:g5T(F);
break;case 33:z=F.O;z.D>1&&(--z.D,dE(z).O=0);break;case 36:z=F.O;b=dE(z);for(C=0;C<=15;C++)for(F=0;F<=32;F++)if(z.A[C][F]===b){for(;F<=32;F++)z.A[C][F].reset();break}break;case 37:BH(F,2,z);break;case 38:BH(F,3,z);break;case 39:BH(F,4,z);break;case 40:PH(F.O,0,32);break;case 41:z=F;z.style.set(2);z.O=z.D;z.O.O=0;z.O.style=z.style;z.A.mode=1<<z.O.N;break;case 42:z=F;b=z.text;b.O=15;b.style.set(4);s3(b);KoV(z);break;case 43:KoV(F);break;case 44:b=F;C=b.D;switch(b.style.get()){case 1:case 2:case 3:pv(C,
z)}q4(C,0,15);break;case 45:b:{C=F;b=C.O;switch(C.style.get()){default:case 2:case 1:break b;case 4:if(b.row<15){++b.row;b.D=1;break b}break;case 3:}b.O<2&&(b.O=2,b.row<b.O&&(b.row=b.O));C=b.row-b.O+1;pv(b,z);V4y(b,C,C+1,b.O-1);q4(b,b.row,1)}break;case 46:q4(F.N,0,15);break;case 47:b=F,pv(b.D,z),b.N.updateTime(b.A.time+0),z=b.N,b.N=b.D,b.D=z,g5T(b)}break;case 7:switch(C){case 33:case 34:case 35:z=F.O,(z.D+=C&3)>32&&(z.D=32)}}},M4n=function(b,C,F,z,N,h,H){var c=h[0],r=H[c.getAttribute("p")];
if(r.gi===1){var L=h[1],K=h[2];h=h[3];c.getAttribute("t");L.getAttribute("t");K.getAttribute("t");h.getAttribute("t");c.getAttribute("p");L.getAttribute("p");h.getAttribute("p");H=H[K.getAttribute("p")];c=DAl(c.textContent,L.textContent,K.textContent,h.textContent,H);return new j1(b,C,N,F,c,z,r)}switch(r.gi){case 9:case 10:r.textEmphasis=1;break;case 11:r.textEmphasis=2;break;case 12:r.textEmphasis=3;break;case 13:r.textEmphasis=4;break;case 14:r.textEmphasis=5}return new j1(b,C,N,F,c.textContent||
"",z,r)},DAl=function(b,C,F,z,N){var h=g.u9(),H=h?g.Nv("DIV"):g.Nv("RUBY"),c=g.Nv("SPAN");
c.textContent=b;H.appendChild(c);b=h?g.Nv("DIV"):g.Nv("RP");b.textContent=C;H.appendChild(b);C=h?g.Nv("DIV"):g.Nv("RT");C.textContent=F;H.appendChild(C);F=N.gi;if(F===10||F===11||F===12||F===13||F===14)if(g.xO(C,"text-emphasis-style","filled circle"),g.xO(C,"text-emphasis-color","currentcolor"),g.xO(C,"webkit-text-emphasis","filled circle"),N.gi===11||N.gi===13)g.xO(C,"webkit-text-emphasis-position","under left"),g.xO(C,"text-emphasis-position","under left");F=!0;if(N.gi===4||N.gi===7||N.gi===12||
N.gi===14)g.xO(H,"ruby-position","over"),g.xO(H,"-webkit-ruby-position","before");else if(N.gi===5||N.gi===6||N.gi===11||N.gi===13)g.xO(H,"ruby-position","under"),g.xO(H,"-webkit-ruby-position","after"),F=!1;N=h?g.Nv("DIV"):g.Nv("RP");N.textContent=z;H.appendChild(N);h&&(z=F,g.xO(H,{display:"inline-block",position:"relative"}),h=H.firstElementChild.nextElementSibling,g.xO(h,"display","none"),h=h.nextElementSibling,g.xO(h,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.xO(H.lastElementChild,"display","none"),z?(g.xO(H,"padding-top","0.6em"),g.xO(h,"top","0")):(g.xO(H,"padding-bottom","0.6em"),g.xO(h,"bottom","0")));return H},pWO=function(b){var C="_"+fv++;
return new $b(0,0x8000000000000,0,C,b)},lM=function(b,C){b=b.getAttribute(C);
if(b!=null)return Number(b)},kb=function(b,C){b=b.getAttribute(C);
if(b!=null)return b==="1"},iM=function(b,C){b=lM(b,C);
return b!==void 0?b:null},yZ=function(b,C){b=b.getAttribute(C);
if(b!=null)return oD.test(b),b},dAT=function(b,C){var F={},z=C.getAttribute("ws");
Object.assign(F,z?b.W[z]:b.N);b=iM(C,"mh");b!=null&&(F.DN=b);b=iM(C,"ju");b!=null&&(F.textAlign=b);b=iM(C,"pd");b!=null&&(F.Gi=b);b=iM(C,"sd");b!=null&&(F.Mi=b);b=yZ(C,"wfc");b!=null&&(F.windowColor=b);C=lM(C,"wfo");C!==void 0&&(F.windowOpacity=C/255);return F},PGs=function(b,C){var F={},z=C.getAttribute("wp");
z&&Object.assign(F,b.B[z]);b=iM(C,"ap");b!=null&&(F.Y4=b);b=lM(C,"cc");b!=null&&(F.u5=b);b=lM(C,"ah");b!=null&&(F.gO=b);b=lM(C,"rc");b!=null&&(F.nK=b);C=lM(C,"av");C!=null&&(F.vx=C);return F},qRU=function(b,C,F,z){var N={};
Object.assign(N,PGs(b,C));Object.assign(N,dAT(b,C));z?g.mn(N,b.N)?(z=b.G,N=b.N):z="_"+fv++:z=C.getAttribute("id")||"_"+fv++;b=lM(C,"t")+F;C=lM(C,"d")||0x8000000000000;if(N.Gi===2||N.Gi===3)F=N.nK,N.nK=N.u5,N.u5=F;return new $b(b,C,0,z,N)},O3=function(b){b=g.f_(Math.round(b),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-b.length)+b},siU=function(b,C,F,z,N){z===0&&(z=0x8000000000000);
var h={};C.wpWinPosId&&Object.assign(h,b.N.get(C.wpWinPosId));C.wsWinStyleId&&Object.assign(h,b.G.get(C.wsWinStyleId));b=C.rcRowCount;b!==void 0&&(h.nK=b);C=C.ccColCount;C!==void 0&&(h.u5=C);if(h.Gi===2||h.Gi===3)C=h.nK,h.nK=h.u5,h.u5=C;return new $b(F,z,0,N,h)},TG=function(b){var C=b.byteOffset;
b.byteOffset+=1;return b.O.getUint8(C)},xb=function(b){var C=b.byteOffset;
b.byteOffset+=4;return b.O.getUint32(C)},fFy=function(b){if(typeof b==="string")return!1;
b=new Bu5(b,0);return jiV(b)},jiV=function(b){if(!(b.byteOffset<b.O.byteLength)||xb(b)!==1380139777)return!1;
b.version=TG(b);if(b.version>1)return!1;TG(b);TG(b);TG(b);return!0},$Ab=function(b,C){if(!C)return"";
b.N&&b.D.params.Mi!==1&&(C*=-1);return`translate${b.N?"X":"Y"}(${C}px)`},lF5=function(b){b.tA=Array.from(b.element.getElementsByClassName("caption-visual-line"));
for(var C=b.D.params.nK,F=0,z=0,N=b.tA.length-1;F<C&&N>-1;){var h=b.tA[N];z+=b.N?h.offsetWidth:h.offsetHeight;F++;N--}b.DQ=z;C=Math;F=C.max;isNaN(b.ej)&&((z=b.O.u5)?(N=g.Nv("SPAN"),g.nC(N,"\u2013".repeat(z)),g.xO(N,Ity(b,b.O.JM)),b.A.appendChild(N),b.ej=N.offsetWidth,b.A.removeChild(N)):b.ej=0);z=b.A;b.AA=F.call(C,b.ej,b.CX,(b.N?z.offsetHeight:z.offsetWidth)+1)},kl3=function(b,C){lF5(b);
var F=b.tA.reduce((z,N)=>(b.N?N.offsetWidth:N.offsetHeight)+z,0);
F=b.DQ-F;if(F!==b.hA){let z=F>0&&b.hA===0,N=F<b.hA;C||isNaN(F)||z||!N||(g.jQ(b.element,"ytp-rollup-mode"),b.Y(b.element,"transitionend",b.QD));g.xO(b.A,"transform",$Ab(b,F));b.hA=F}lF5(b)},o5k=function(b,C,F,z){var {formatId:N,
vv:h,startTimeMs:H,durationMs:c}=b.mf(C),r={formatId:N,startTimeMs:H,durationMs:c,wJ:h,sR:h},L=iFV(b.xw,r.startTimeMs),K=L>=0?b.xw[L]:null,D=K?K.startTimeMs+K.durationMs:0,P=r.startTimeMs+r.durationMs;!K||r.startTimeMs-D>b.N?b.xw.splice(L+1,0,r):(K.durationMs=Math.max(D,P)-K.startTimeMs,K.sR=Math.max(K.sR,r.sR));z(b.xw);z=g.lH(C);b=b.G;z=z.buffer.slice(z.byteOffset,z.byteLength+z.byteOffset);C=C.info.N;b.AA?b.B==null?g.N8(b.logger,350058965,"Null loaded track meta data at captions data received"):
F.oV(z,b.B,C*1E3):g.N8(b.logger,350058965,"Null Representation at captions data received")},Tul=function(b,C){b.D=(F,z)=>{if(b.X.U().experiments.Yf("html5_sabr_live_support_subfragmented_captions"))(b.O?b.O=b.O.G(F):(b.O=F,yQl(b.O)),b.O)?F.info.Zx&&(OF7(b.O),o5k(b,b.O,C,z),b.O=null):g.N8(b.logger,350058965,"Empty slice");
else if(F.info.Zx){var N=F;if(b.XG.length>0){for(N=b.XG.shift();b.XG.length>0;)N=N?.G(b.XG.shift());N=N?.G(F)}N?(yQl(N),OF7(N),o5k(b,N,C,z)):g.N8(b.logger,350058965,"Empty slice")}else b.XG.push(F)};
b.X.addEventListener("sabrCaptionsDataLoaded",b.D)},iFV=function(b,C){b=g.Dl(b,{startTimeMs:C},(F,z)=>F.startTimeMs-z.startTimeMs);
return b>=0?b:-b-2},yQl=function(b){try{var C=g.or(b)*1E3}catch(F){C=b.info.segmentStartTime*1E3}C<0&&(C=b.info.segmentStartTime*1E3);
b.info.segmentStartTime=C/1E3;b.info.N=C/1E3},OF7=function(b){try{var C=g.$8j(b)*1E3}catch(F){C=b.info.A*1E3}C<0&&(C=b.info.A*1E3);
b.info.A=C/1E3;b.info.K=C/1E3},xAn=function(b,C){if(!g.wqj(b)||b.O!=null&&g.CY(C,b.O)&&b.O.O.rawcc!=null)return!1;
C=!!b.O&&b.O.isManifestless&&Object.values(b.O.O).some(F=>g.FW(F,"386"));
b=!!b.O&&!b.O.isManifestless&&g.bmn(b.O);return C||b},XW5=function(b,C,F){var z=[];
for(let N in b.D.O){if(!b.D.O.hasOwnProperty(N))continue;let h=b.D.O[N];if(g.FW(h,F||null)){let H=h.info.captionTrack;H&&H.languageCode===C&&z.push(h)}}return z.length?z[0]:null},WoT=function(b,C){var F=[];
for(let N in b.D.O){if(!b.D.O.hasOwnProperty(N))continue;var z=b.D.O[N];if(g.FW(z,C||null)){let h=z.info.id,H=h,c=`.${h}`,r="",L="";if(z=z.info.captionTrack)h=z.languageCode,H=z.displayName,c=z.vssId,r=z.kind,L=z.id;F.push(new g.es({id:N,languageCode:h,languageName:H,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:c,kind:r,captionId:L}))}}return F},UAT=function(b){var C=emn.length;
if(b.byteLength<C)return!1;b=new Uint8Array(b,0,C);for(let F=0;F<C;F++)if(emn[F]!==b[F])return!1;return!0},X5=function(b){b=b.split(":");
var C=0;for(let F of b)C=C*60+Number(F);return C*1E3},Rm5=function(b,C,F,z){z=Object.assign({DN:0},z);
return new $b(b,C,F,"_"+fv++,z)},v5y=function(b,C,F,z,N,h,H,c,r){switch(H.tagName){case "b":c.bold=!0;
break;case "i":c.italic=!0;break;case "u":c.underline=!0}for(let K=0;K<H.childNodes.length;K++){var L=H.childNodes[K];if(L.nodeType===3)L=new j1(C,F,z,N.id,L.nodeValue,h||K>0,g.vs(c)?void 0:c),r.push(L),N.O.push(L);else{let D={};Object.assign(D,c);v5y(b,C,F,z,N,!0,L,D,r)}}},JQl=function(b,C,F){if(typeof C==="string"||fFy(C))return[{trackData:C,
gU:F}];if(typeof C==="string"&&C.substring(0,6)==="WEBVTT"||typeof C!=="string"&&UAT(C))return[{trackData:C,gU:F}];var z=new DataView(C);if(z.byteLength<=8||z.getUint32(4)!==1718909296)return[];var N=g.xzf(z);if(b.Bw&&N){var h=g.sr(N),H=g.Bq(N);N=N.segmentNumber;h&&N&&b.Bw.iR(N,h,H)}b=g.Tg(z,1835295092);if(!b||!b.length||!b[0].size)return[];h=[];for(H=0;H<b.length;H++)N=b[H],N=new Uint8Array(C,N.dataOffset,N.size-(N.dataOffset-N.offset)),N=g.gz(N),h.push({trackData:N,gU:F+H*1E3});AQn(z,h,F);return h=
h.filter(c=>!!c.trackData)},SRb=function(b,C,F){b.O||(b.O=new mAn);
b=b.O.A(C,F);Math.random()<.01&&g.F0(Error("Deprecated subtitles format in web player: WebVTT"));return b},AQn=function(b,C,F){var z=g.kU(b,0,1836476516),N=9E4;
z&&(N=g.i8(z)||9E4);z=0;var h=g.Tg(b,1836019558);for(let c=0;c<h.length;c++){var H=h[c];c<C.length&&(H=g.kU(b,H.dataOffset,1953653094))&&(H=g.kU(b,H.dataOffset,1952867444))&&(H=g.Or(H)/N*1E3,c===0&&(z=H),C[c].gU=H-z+F||F*c*1E3)}},aF3=function(b){var C={};
if(b=g.AL(b))C.lang=b,g.teu.test(b)&&(C.Gi=1);return C},WH=function(b){return b.A==="HLS"&&b.lS?!0:b.ZQ&&b.lS&&b.A!=="LIVE"&&b.A!=="SABR_LIVE"},ugO=function(b){return!b.N&&b.ZQ&&b.Hv&&(b.A==="LIVE"||b.A==="SABR_LIVE")},e1=function(b,C,F=!1){var z=b.V.C("enable_player_captions_new_style_defaults")?ZFb:wW5,N=z.JM;
b.G={};Object.assign(b.G,z);b.G.JM={};Object.assign(b.G.JM,N);b.Z={JM:{}};var h=C.backgroundOverride?b.Z:b.G,H=C.background||N.background;oD.test(H);h.JM.background=H;h=C.colorOverride?b.Z:b.G;H=C.color||N.color;oD.test(H);h.JM.color=H;h=C.windowColorOverride?b.Z:b.G;H=C.windowColor||z.windowColor;oD.test(H);h.windowColor=H;h=C.backgroundOpacityOverride?b.Z:b.G;H=C.backgroundOpacity;H==null&&(H=N.backgroundOpacity);h.JM.backgroundOpacity=H;h=C.fontSizeIncrementOverride?b.Z:b.G;H=C.fontSizeIncrement;
H==null&&(H=N.fontSizeIncrement);h.JM.fontSizeIncrement=H;H=C.fontStyleOverride?b.Z:b.G;h=C.fontStyle;h==null&&(h=N.bold&&N.italic?3:N.bold?1:N.italic?2:0);H=H.JM;switch(h){case 1:H.bold=!0;delete H.italic;break;case 2:delete H.bold;H.italic=!0;break;case 3:H.bold=!0;H.italic=!0;break;default:delete H.bold,delete H.italic}h=C.textOpacityOverride?b.Z:b.G;H=C.textOpacity;H==null&&(H=N.textOpacity);h.JM.textOpacity=H;h=C.windowOpacityOverride?b.Z:b.G;H=C.windowOpacity;H==null&&(H=z.windowOpacity);h.windowOpacity=
H;z=C.charEdgeStyleOverride?b.Z:b.G;h=C.charEdgeStyle;h==null&&(h=N.charEdgeStyle);z.JM.charEdgeStyle=h;z=C.fontFamilyOverride?b.Z:b.G;h=C.fontFamily;h==null&&(h=N.fontFamily);z.JM.fontFamily=h;b.loaded&&b.cv();F&&g.i6("yt-player-caption-display-settings",C,2592E3)},U3=function(b,C,F){C&&!b.lB?(C=pWO({Gi:0,
lang:"en"}),b.lB=[C,new j1(C.start,C.end-C.start,0,C.id,F??"Captions look like this")],b.player.Vw(b.lB)):!C&&b.lB&&(E5V(b,b.lB),b.lB=null)},IFk=function(b){if(b.V.C("enable_player_captions_persistence_state_machine")){var C=g.oj("yt-player-caption-persistence");
if(C==null){let F=g.Wt().iB(65);if(F===!0)C=!1;else{let z=g.FH(b.V)?RD(b):t4O(b);z!=null?C=!!z:F===!1&&(C=!0)}C!==void 0&&JZ(b,C)}return C}},RD=function(b){if(!b.X.isInline())return g.oj("yt-player-sticky-caption")},t4O=function(b){if(!b.storage)return null;
try{var C=b.storage.get("module-enabled")}catch(F){b.storage.remove("module-enabled")}return C},mO=function(b){if(b.V.C("enable_player_captions_persistence_state_machine"))return IFk(b);
var C=void 0,F=g.Wt().iB(65);if(g.FH(b.V)&&F!=null){if(RD(b)!=null)return!1;C=!F}return C},Glb=function(b){if(b.V.Rh===1||b.videoData.rN===1||g.lR(b.videoData,"yt:cc")==="alwayson")return!0;
if(b.videoData.captionTracks.length)var C=b.getAudioTrack().D;if(b.V.C("enable_player_captions_persistence_state_machine")){var F=IFk(b);if(F!==void 0)return!!F}else if(b.V.Rh===2&&(g.FH(b.V)?F=RD(b):F=t4O(b),F!=null))return!!F;F=gE(b.player.getAudioTrack(),g.FH(b.V));var z=g.lR(b.videoData,"yt:cc");if(mO(b)===void 0){if(F==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return z?z==="on":!0;if(F==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return z==="on"}else return z==="on";return C==="ON"||g.lR(b.videoData,
"yt:cc")==="on"},S1=function(b,C=!1){if(b.D&&!C||!b.videoData.captionTracks.length)return!1;
b=b.getAudioTrack();return!!b.O||b.D==="FORCED_ON"},QiB=function(b,C){if(b.D){var F=b.X.Yn().kw().textTracks,z=null;
b.A==="HLS"?z=b.D.getId():z=b.D.toString();for(let h=0;h<F.length;h++){var N=F[h];N.id===z&&(C?N.mode!=="showing"&&(N.mode="showing",N=b.D,b.Mv(N,!!N,aD(b)?"g":b.K?"m":"s")):N.mode==="showing"&&(N.mode="disabled"))}}},aD=function(b){var C=uM(b);
return!!C&&b.D===C},bJ5=function(b,C){if(b.A==="HLS")return!1;
g.Xq(b.videoData)&&(C=!0);C||(C=b.A==="TTS"?!1:b.A==="INNERTUBE"?!1:!0);return C||b.V.C("web_watch_disable_account_level_captions_settings")&&g.FH(b.V)?!0:!!g.Wt().iB(66)},uM=function(b){return b.W&&b.W.O},Zz=function(b,C){if(!b.O)return null;
if(b.W&&b.W.N)return b.W.N;C=bJ5(b,C);C=g.xP(b.O.O,C);var F=null;if(WB5(b.V)){var z=b.X.isInline()?void 0:g.oj("yt-player-caption-sticky-language");var N=[z,b.videoData.captionsLanguagePreference,b.V.captionsLanguagePreference,g.lR(b.videoData,"yt:cc_default_lang")];let c=!1;for(let r=0;r<N.length;r++){let L=N[r];if(L){c=!0;for(var h=0;h<C.length;h++)if(g.AL(C[h])===L)return C[h];for(h=0;h<C.length;h++)if(g.AL(C[h]).split("-")[0]===L.split("-")[0])return C[h]}}if(c&&b.O&&(N=b.O.W,N.length))for(var H of N)if(H.languageCode===
z){F=H;break}}else for(H=[b.videoData.captionsLanguagePreference,b.V.captionsLanguagePreference,g.lR(b.videoData,"yt:cc_default_lang")],z=0;z<H.length;z++)for(N=0;N<C.length;N++)if(g.AL(C[N])===H[z])return C[N];H=null;b.W&&b.W.A&&(H=b.W.A);H||(H=C.find(c=>c.isDefault)||null);
H||(H=C[0]||uM(b));H&&F&&g.AL(H).split("-")[0]!==F.languageCode.split("-")[0]&&(H=XST(H,F));return H},ID=function(b,C,F){b.loaded&&b.unload();
F!=null&&(b.K=F,b.K&&(b.V.C("enable_player_captions_persistence_state_machine")?JZ(b,!!C):g.FH(b.V)?wE(b,!!C):E3(b,!!C)));C!==null||S1(b,!0)||b.Mv(C,!!C,b.K?"m":"s");b.D=C;S1(b)&&(b.D=uM(b));tZ(b,b.D??void 0);b.load()},JZ=function(b,C){b.V.C("enable_player_captions_persistence_state_machine")&&g.i6("yt-player-caption-persistence",C,3122064E3)},wE=function(b,C){b.X.isInline()||g.i6("yt-player-sticky-caption",C,2592E3)},E3=function(b,C){if(b.storage)try{b.storage.set("module-enabled",C)}catch(F){}},
tZ=function(b,C){b.V.C("html5_modify_caption_vss_logging")&&(b.videoData.b$=C)},Fmn=function(b,C){var F=b.NT[C.id];
F&&F.D!==C&&(F.dispose(),delete b.NT[C.id],F=null);F||(F=Chl(b,C))&&(b.NT[C.id]=F)},zrT=function(b,C){var F=C.windowId;
b.LJ[F]||(b.LJ[F]=[]);b.LJ[F].push(C)},Chl=function(b,C){var F=NlT(b);
if(!F)return null;var z=b.D?g.AL(b.D):null;z&&g.teu.test(z)&&(C.params.Gi=1);var N=b.QD.getPlayerSize();z=N.height*b.AA.height;N=N.width*b.AA.width;b.V.playerStyle!=="google-live"||b.G.isDefault||Object.assign(C.params,b.G);switch(C.params.DN!=null?C.params.DN:C.O.length>1?1:0){case 1:return new hrB(C,b.G,b.Z,F.width,F.height,N,z,b.V.experiments,b.Et.bind(b),b.X);case 2:return new HJs(C,b.G,b.Z,F.width,F.height,N,z,b.V.experiments,b.Et.bind(b),b.X);default:return new GG(C,b.G,b.Z,F.width,F.height,
N,z,b.V.experiments,b.Et.bind(b),b.X)}},NlT=function(b){var C=b.QD.getVideoContentRect(!0).height,F=b.QD.getVideoContentRect(!0).width;
if(!C||!F)return null;C*=b.AA.height;F*=b.AA.width;return{width:F,height:C}},E5V=function(b,C){b.player.l_(C);
for(let F of C)g.z3(b.ej,F);VZ(b.XS)},c17=function(b,C){if(!b.O)return{};
if(C){g.vs(C)||b.pZ(C.vss_id,"m");if(b.N&&b.A!=="HLS"||!g.Bu(C))return;if(g.vs(C)){ID(b,null,!0);return}let z;var F=g.xP(b.O.O,!0);for(let N=0;N<F.length;N++){let h=F[N];h.languageCode!==C.languageCode||z&&(h.languageName!==C.languageName||(h.captionId||"")!==(C.captionId||"")||g.Rh(h)!==C.displayName)||(z=C.translationLanguage?XST(h,C.translationLanguage):h)}b.hk(C.position);!z||z===b.D&&b.loaded||(C=g.y0(),F=g.AL(z),C.length&&F===C[C.length-1]||(C.push(F),g.i6("yt-player-caption-language-preferences",
C)),WB5(b.V)&&!b.X.isInline()&&g.i6("yt-player-caption-sticky-language",F,2592E3),ID(b,z,!0))}else return b.loaded&&b.D&&!aD(b)?g.vp(b.D):{};return""};
g.b4.prototype.iR=g.Nm(72,function(b,C,F){this.D.set(b,{UT:C,Vg:F})});
g.Cz.prototype.iR=g.Nm(71,function(b,C,F){this.AA.iR(b,C,F)});
g.va.prototype.DQ=g.Nm(70,function(){return!1});
g.va.prototype.N=g.Nm(69,function(){});
g.Aw.prototype.N=g.Nm(68,function(b,C,F){this.gI();C=this.Z(b,C);var z=this.Ut.U().C("html5_report_captions_ctmp_qoe"),N=(0,g.u)();this.A();xX7(this,C,{format:"RAW",onSuccess:h=>{this.D=null;if(z){var H=(h.responseText.length/1024).toFixed();let c=(0,g.u)();this.videoData.FS("capresp",{ms:c-N,kb:H})}H=h.getResponseHeader&&h.getResponseHeader("Content-Length")?Number(h.getResponseHeader("Content-Length")):0;F.oV(h.responseText,b,void 0,void 0,H)},
onError:z?h=>{this.videoData.FS("capfail",{status:h?.status??0})}:void 0,
withCredentials:!0})});
g.Jw.prototype.N=g.Nm(67,function(b,C,F){this.gI();C=this.Z(b,C);this.A();this.D=g.sN(C,{format:"RAW",onSuccess:z=>{this.D=null;var N=z.getResponseHeader&&z.getResponseHeader("Content-Length")?Number(z.getResponseHeader("Content-Length")):0;F.oV(z.responseText,b,void 0,void 0,N)},
withCredentials:!0})});
g.D_.prototype.K=g.Nm(66,function(){this.mediaElement.K()});
g.nV.prototype.K=g.Nm(65,function(){var b=g.Sf(document,"track",void 0,this.O);for(let C=0;C<b.length;C++)g.LC(b[C])});
g.D_.prototype.hA=g.Nm(64,function(){return this.mediaElement.hA()});
g.nV.prototype.hA=g.Nm(63,function(){return!(!this.O.textTracks||!this.O.textTracks.addEventListener)});
g.D_.prototype.KJ=g.Nm(62,function(){return this.mediaElement.KJ()});
g.nV.prototype.KJ=g.Nm(61,function(){return!!this.O.textTracks});
g.D_.prototype.lB=g.Nm(60,function(b){this.mediaElement.lB(b)});
g.nV.prototype.lB=g.Nm(59,function(b){for(let C=0;C<b.length;C++)this.O.appendChild(b[C])});
g.Dk.prototype.pZ=g.Nm(45,function(b,C){this.app.fJ().pZ(b,C)});
g.Ud.prototype.pZ=g.Nm(44,function(b,C){this.Ot.pZ(b,C)});
g.Ox.prototype.pZ=g.Nm(43,function(b,C){b=[b,C];g.rJ(this,g.n5(this.provider),"cfi",b)});
g.xq.prototype.pZ=g.Nm(42,function(b,C){this.qoe&&this.qoe.pZ(b,C)});
g.aW.prototype.pZ=g.Nm(41,function(b,C){this.Yw.pZ(b,C)});
g.tw.prototype.pZ=g.Nm(40,function(){});
g.eP.prototype.pZ=g.Nm(39,function(b,C){g.VP(this,37,[b,C])});
g.Dk.prototype.Mv=g.Nm(38,function(b,C,F){this.app.fJ().Mv(b,C,F)});
g.Ud.prototype.Mv=g.Nm(37,function(b,C,F){this.Ot.Mv(b,C,F)});
g.Ox.prototype.Mv=g.Nm(36,function(b,C,F){if(this.ZQ!==b||this.lS!==C)C=C==="rawcc"?"":C,F=[b,C,this.ZQ,F],g.rJ(this,g.n5(this.provider),"cfs",F),this.ZQ=b,this.lS=C});
g.xq.prototype.Mv=g.Nm(35,function(b,C,F){this.qoe&&this.qoe.Mv(b,C,F)});
g.aW.prototype.Mv=g.Nm(34,function(b,C,F){this.Yw.Mv(b,C,F)});
g.tw.prototype.Mv=g.Nm(33,function(){});
g.eP.prototype.Mv=g.Nm(32,function(b,C,F){g.VP(this,36,[b,C,F])});
g.FC.prototype.ZF=g.Nm(9,function(b){return(b=this.A(b))?b.O:0});
g.hw.prototype.ZF=g.Nm(8,function(){return 0});
var v$T=/#(.)(.)(.)/,R87=/^#(?:[0-9a-f]{3}){1,2}$/i,r1U={en:"English"},LmO=class extends g.va{constructor(b){super(b);this.D=new Set}G(b){var C=this.Ut.Yn();if(C&&C.kw()){C=C.kw().textTracks;for(let F of C)F.kind==="subtitles"&&!this.D.has(F.language)&&F.language&&(g.b2(this.O,new g.es({languageCode:F.language,languageName:F.language,kind:F.kind,id:F.id,displayName:r1U[F.label]||F.label,vss_id:`.${F.language}`})),this.D.add(F.language))}g.xP(this.O).length>0&&b.GP()}},Yq5=class{constructor(){this.segments=
[]}contains(b){b=g.Dl(this.segments,b);return b>=0||b<0&&(-b-1)%2===1}length(){return this.segments.length/2}},nJn=class extends g.pu{constructor(b,C,F,z,N,h){super();this.policy=b;this.player=C;this.JA=F;this.B=z;this.G=N;this.DQ=h;this.N=new Yq5;this.Z=-1;this.D=this.A=this.O=null;this.AA=0;this.K=new g.D5(this.lB,1E3,this);this.events=new g.d7(this);g.R(this,this.K);g.R(this,this.events);this.events.Y(C,"SEEK_COMPLETE",this.W);this.W();this.lB()}GD(){super.GD();this.D&&this.D.cancel()}W(){this.seekTo(this.player.getCurrentTime())}seekTo(b){b-=
this.player.LX();var C=this.O;this.O=g.vu(this.JA.K(b).uB);C!==this.O&&this.DQ&&this.DQ()}reset(){this.N=new Yq5;this.Z=-1;this.D&&(this.D.cancel(),this.D=null)}lB(){this.gI();var b;if(b=this.O!=null)b=this.O,b=b.JA.N(b);if(b&&!this.D&&!(this.O&&this.O.segmentStartTime-this.player.getCurrentTime()>30)){b=this.O;b=b.JA.ZQ(b);let N=b.uB[0];if(this.player.getVideoData()?.enableServerStitchedDai){var C=this.player.R4();if(C){var F=N.JA.info.id;let h=N.vv;var z=b.uB[0].N;if(this.policy.XS){if(C=g.Y4O(C,
z,h,F,3))b.N=C}else if(F=C.lE(z,h,F,3))if(z=2,C.f8.has(h)?z=0:g.eu(C,h)&&(z=1),C=z,C===0)F&&(b.O=new g.F1(F));else if(C===2){this.K.start();mX3(this)&&this.seekTo(this.player.getCurrentTime());return}}}N.JA.index.lJ(N.vv)?(this.N.contains(b.uB[0].vv)||SyU(this,b),this.O=g.vu(b.uB)):mX3(this)&&this.seekTo(this.player.getCurrentTime())}this.K.start()}},Vzn=class extends g.va{constructor(b,C){super(C);this.D=b;this.X=C;this.B=null;this.lB=!1;this.logger=new g.zh("caps");this.AA=g.CY(this.X,this.D)}N(b,
C,F){this.A();C=atb(this,b.getId());C||(C=b.languageCode,C=this.D.isManifestless?upB(this,C,"386"):upB(this,C));if(C){var z=(C.index.ZF(C.index.Wx())-C.index.getStartTime(C.index.Wx()))*1E3,N=new g.mxJ(this.X.U());this.B=new nJn(N,this.X,C,(h,H)=>{F.oV(h,b,H,z)},this.AA||g.M8(C.info),()=>{this.B&&this.B.reset();
this.lB=!0})}}DQ(){var b=this.lB;
this.lB=!1;return b}G(b){var C=this.X.U().C("html5_fallback_if_rawcc_missing");var F=this.D.O.rawcc!=null;if(!this.AA||!F&&C)C=this.D.isManifestless?ZWn(this,"386"):ZWn(this);else{if(!F){g.N8(this.logger,386248249,"rawcc used but unavailable");return}C=[new g.es({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.es({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(let z of C)g.b2(this.O,
z);b.GP()}A(){this.B&&(this.B.dispose(),this.B=null)}Z(){return""}},oD=/^#(?:[0-9a-f]{3}){1,2}$/i;var gJl=["left","right","center","justify"];var j1=class extends g.mR{constructor(b,C,F,z,N,h=!1,H=null){super(b,b+C,{priority:F,namespace:"captions"});this.windowId=z;this.text=N;this.append=h;this.O=H}toString(){return super.toString()}};var GG=class extends g.Q{constructor(b,C,F,z,N,h,H,c,r,L){var K=L.isInline()&&!0,D={};Object.assign(D,C);Object.assign(D,b.params);Object.assign(D,F);var P={};Object.assign(P,C.JM);b.params.JM&&Object.assign(P,b.params.JM);Object.assign(P,F.JM);K&&(D.windowOpacity=.6,P.backgroundOpacity=0);D.JM=P;var M=D.Gi===1,f=[{J:"span",L:"captions-text",S:{style:"word-wrap: normal; display: block;"}}],U=c.Yf("caption_edit_on_hover")&&L.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
U&&f.unshift({J:"button",L:"caption-edit",S:{tabindex:"0","aria-label":A65()},j:[{J:"svg",S:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},j:[{J:"path",S:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({J:"div",L:"caption-window",S:{id:`caption-window-${b.id}`,dir:M?"rtl":"ltr",tabindex:"0",lang:D.lang},j:f});this.experiments=
c;this.K=[];this.XS=!1;this.D=b;this.KJ=this.ZQ=null;this.oX=h;this.tP=H;this.G=null;this.maxWidth=h*.96;this.maxHeight=H*.96;this.O=D;this.h8=F;this.NT=C;this.A=this.pJ("captions-text");b=this.A.style;this.LJ=c.Yf("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in b||"WebkitBoxDecorationBreak"in b);this.xf=wSV(z,N,h,H);this.Z1=r;U&&(this.Z=this.pJ("caption-edit"),this.Y(this.Z,"click",()=>{this.Z1()}));
this.type=0;this.Et=this.xf*E$O(P);this.KX=K;this.Hv=c.Yf("enable_centered_caption_for_tvfilm_video")&&L.getVideoData().isTvfilmVideo;this.W=L.U().wI().O.iB(g.jUY);z=new g.W8(this.element,!0);g.R(this,z);z.subscribe("dragstart",this.Sx,this);z.subscribe("dragmove",this.ER,this);z.subscribe("dragend",this.CF,this);this.cv=this.qT=this.GK=this.lS=0;z="";this.O.windowOpacity&&(z=Kv(this.O.windowColor),z="rgba("+z[0]+","+z[1]+","+z[2]+","+this.O.windowOpacity+")");N={"background-color":z,display:this.O.isVisible===
!1?"none":"","text-align":gJl[this.O.textAlign]};this.LJ&&(N["border-radius"]=z?`${this.Et*.25}px`:"");(this.N=this.D.params.Gi===2||this.D.params.Gi===3)&&tqb(this,this.element);g.xO(this.element,N);K&&this.element.parentElement?.style.setProperty("--caption-window-color",z);switch(this.O.Y4){case 0:case 1:case 2:g.jQ(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.jQ(this.element,"ytp-caption-window-bottom")}}Sx(b,C){this.qT=b;this.cv=C;var F=g.wX(this.element,this.element.parentElement);
this.lS=b-F.x;this.GK=C-F.y}ER(b,C){if(b!==this.qT||C!==this.cv){g.B4(this.element,"ytp-dragging")||g.jQ(this.element,"ytp-dragging");var F=g.t8(this.element);b=b-this.lS-.02*this.oX;var z=C-this.GK-.02*this.tP,N=(b+F.width/2)/this.maxWidth*3;N=Math.floor(g.f_(N,0,2));var h=(z+F.height/2)/this.maxHeight*3;h=Math.floor(g.f_(h,0,2));C=N+h*3;b=(b+N/2*F.width)/this.maxWidth;b=g.f_(b,0,1)*100;F=(z+h/2*F.height)/this.maxHeight;F=g.f_(F,0,1)*100;this.D.params.Y4=C;this.D.params.vx=F;this.D.params.gO=b;this.D.params.isDefault=
!1;this.O.Y4=C;this.O.vx=F;this.O.gO=b;this.O.isDefault=!1;this.NT.Y4=C;this.NT.vx=F;this.NT.gO=b;this.NT.isDefault=!1;this.wR()}}CF(){g.$k(this.element,"ytp-dragging")}wR(){this.B(this.K)}B(b){var C=this.KX?0:Math.min(this.MN(),this.maxWidth),F=this.hf(),z=this.KX;if(z){var N=getComputedStyle(this.A.parentNode);N=M4(N.borderLeftWidth)+M4(N.borderRightWidth)+M4(N.paddingLeft)+M4(N.paddingRight)}else N=0;var h=N;N="";this.D.params.Gi===3&&(N="rotate(180deg)");var H=z?`calc(96% - ${h}px)`:"96%";g.xO(this.element,
{top:0,left:0,right:"",bottom:"",width:C?`${C}px`:"",height:F?`${F}px`:"","max-width":H,"max-height":H,margin:"",transform:""});this.rI(b);N={transform:N,top:"",left:"",width:C?`${C}px`:"",height:F?`${F}px`:"","max-width":"","max-height":""};H=this.O.Y4;var c=this.O.gO,r=this.O.vx;this.Hv&&H!=null&&(c=50,H=Math.floor(H/3)*3+1);c=c*.96+2;switch(H){case 0:case 3:case 6:(z=this.O.JM.fontSizeIncrement)&&z>0&&this.O.Gi!==2&&this.O.Gi!==3&&(c=Math.max(c/(1+z*2),2));N.left=`${c}%`;break;case 1:case 4:case 7:N.left=
`${c}%`;c=0;this.W||(c=this.A.offsetWidth);C||c?(C=C||c+1,N.width=`${C}px`,N["margin-left"]=z?`${C/-2-h/2}px`:`${C/-2}px`):(this.W&&(N.width="max-content"),N.transform+=" translateX(-50%)");break;case 2:case 5:case 8:N.right=`${100-c}%`}z=r*.96+2;switch(H){case 0:case 1:case 2:N.top=`${z}%`;break;case 3:case 4:case 5:N.top=`${z}%`;z=0;this.W||(z=this.element.clientHeight);(F=F||z)?(N.height=`${F}px`,N["margin-top"]=`${F/-2}px`):N.transform+=" translateY(-50%)";break;case 6:case 7:case 8:N.bottom=
`${100-z}%`}g.xO(this.element,N);this.Z&&(this.W?F=this.Et:(b=GLb(this,b),F=this.Hv?b>0?this.A.offsetHeight/b:0:this.A.offsetHeight/b),this.Z.style.height=`${F}px`,this.Z.style.width=`${F}px`,this.element.style.paddingLeft=`${F+5}px`,this.element.style.paddingRight=`${F+5}px`,this.W||(b=Number(this.element.style.marginLeft.replace("px",""))-F-5,F=Number(this.element.style.marginRight.replace("px",""))-F-5,this.element.style.marginLeft=`${b}px`,this.element.style.marginRight=`${F}px`))}rI(b){if(this.type===
0&&this.D.params.nK!==void 0&&this.experiments.Yf("web_enable_popon_asr_captions")){var C=b,F=this.D.params.nK;if(C.length===0||F<=0)b=[];else{b=[];for(let N=C.length-1;N>=0;N--){var z=C[N];b.unshift(z);let h=GLb(this,b);if(h>F){b.shift();typeof z.text==="string"&&(C=z.text.split("\n"),F=h-F,C.length-F>0&&(F=C.slice(F),z=new j1(z.start,z.end-z.start,z.priority||0,z.windowId,F.join("\n"),z.append,z.O),b.unshift(z)));break}}}}for(z=0;z<b.length&&b[z]===this.K[z];z++);if(this.XS||this.K.length>z)z=0,
this.XS=!1,this.K=[],this.G=this.KJ=this.ZQ=null,g.cB(this.A);for(;z<b.length;z++)CG3(this,b[z])}MN(){return 0}hf(){return 0}toString(){return super.toString()}};var Dq7=class{constructor(){this.A=this.time=this.mode=this.D=0;this.N=new Kml(this);this.G=new Kml(this);this.O=[];this.clear()}clear(){this.A=this.time=this.mode=0;this.O=[];this.reset()}reset(){this.mode=0;this.N.reset(0);this.G.reset(1)}},Fos=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],Mzn=class{constructor(){this.type=0}set(b){this.type=b}get(){return this.type}},poy=class{constructor(){this.state=this.TM=this.I1=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}ww(){return this.state!==0}matches(b,C){return this.ww()&&b===this.I1&&C===this.TM}},dqb=class{constructor(){this.timestamp=this.O=0}reset(){this.timestamp=
this.O=0}},QZ=class{constructor(b){this.G=b;this.A=[];this.O=this.D=this.row=0;this.style=new Mzn;this.N=0;for(b=0;b<=15;b++){this.A[b]=[];for(let C=0;C<=32;C++)this.A[b][C]=new dqb}}updateTime(b){for(let C=1;C<=15;++C)for(let F=1;F<=32;++F)this.A[C][F].timestamp=b}debugString(){var b="\n";for(let C=1;C<=15;++C){for(let F=1;F<=32;++F){let z=this.A[C][F];b=z.O===0?b+"_":b+String.fromCharCode(z.O)}b+="\n"}return b}reset(b){for(let C=0;C<=15;C++)for(let F=0;F<=32;F++)this.A[C][F].reset();this.N=b;this.O=
0;this.D=this.row=1}},cQT=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],rQV=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Lon=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,
199,200,202,203,235,206,207,239,212,217,249,219,171,187],YRk=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],Ph5=class{constructor(b){this.A=b;this.G=0;this.style=new Mzn;this.Z=new QZ(this.A);this.K=new QZ(this.A);this.text=new QZ(this.A);this.D=this.Z;this.N=this.K;this.O=this.D}reset(b,C){this.G=C;this.style.set(2);this.D=this.Z;this.N=this.K;this.O=this.D;var F=(b<<2)+(C<<1);this.Z.reset(F);this.K.reset(F);this.text.reset((b<<
2)+(C<<1)+1)}},Kml=class{constructor(b){this.O=b;this.G=0;this.A=new Ph5(this.O);this.Z=new Ph5(this.O);this.D=new poy;this.N=this.A}reset(b){this.G=b;this.D.clear();this.N=this.A;this.A.reset(b,0);this.Z.reset(b,1)}};var qqs=class{N(){}};var bZ=class extends g.pu{reset(){}};var $b=class extends g.mR{constructor(b,C,F,z,N){super(b,b+C,{priority:F,namespace:"captions"});this.id=z;this.params=N;this.O=[]}toString(){return super.toString()}},fv=0;var svB=class extends bZ{constructor(b){super();this.N=b;this.pens={};this.B={};this.W={};this.G="_"+fv++;this.K={};this.D=this.O=null;this.Z=!0}reset(){this.K={};this.D=this.O=null;this.Z=!0}A(b,C){b=b.firstChild;b.getAttribute("format");C=C||0;Number.isFinite(C);b=Array.from(b.childNodes);for(var F of b)if(F.nodeType===1)switch(F.tagName){case "head":var z=F;break;case "body":var N=F}if(z){z=Array.from(z.childNodes);for(var h of z)if(h.nodeType===1)switch(h.tagName){case "pen":F=h.getAttribute("id");
z=this.pens;b={};var H=h.getAttribute("p");H&&Object.assign(b,this.pens[H]);H=kb(h,"b");H!=null&&(b.bold=H);H=kb(h,"i");H!=null&&(b.italic=H);H=kb(h,"u");H!=null&&(b.underline=H);H=iM(h,"et");H!=null&&(b.charEdgeStyle=H);H=iM(h,"of");H!=null&&(b.offset=H);H=yZ(h,"bc");H!=null&&(b.background=H);H=yZ(h,"ec");H!=null&&(b.tX=H);H=yZ(h,"fc");H!=null&&(b.color=H);H=iM(h,"fs");H!=null&&H!==0&&(b.fontFamily=H);H=lM(h,"sz");H!==void 0&&(b.fontSizeIncrement=H/100-1);H=lM(h,"bo");H!==void 0&&(b.backgroundOpacity=
H/255);H=lM(h,"fo");H!==void 0&&(b.textOpacity=H/255);H=iM(h,"rb");H!=null&&H!==10&&H!==0&&(b.gi=H>10?H-1:H);H=iM(h,"hg");H!=null&&(b.a5=H);z[F]=b;break;case "ws":z=h.getAttribute("id");this.W[z]=dAT(this,h);break;case "wp":z=h.getAttribute("id"),this.B[z]=PGs(this,h)}}if(N){h=[];N=Array.from(N.childNodes);for(U of N)if(U.nodeType===1)switch(U.tagName){case "w":this.O=qRU(this,U,C,!1);(N=this.K[this.O.id])&&N.end>this.O.start&&(N.end=this.O.start);this.K[this.O.id]=this.O;h.push(this.O);break;case "p":var c=
U;b=C;N=[];z=c.getAttribute("w")||this.G;F=!!kb(c,"a");b=(lM(c,"t")||0)+b;H=lM(c,"d")||5E3;F||(!this.Z&&this.D&&this.D.windowId===z&&this.D.end>b&&(this.D.end=b),this.D&&this.D.text==="\n"&&(this.D.text=""));let W=F?6:5;var r=c.getAttribute("p");r=r?this.pens[r]:null;let A=Array.from(c.childNodes);A.length&&(this.Z=c.getAttribute("d")!=null);for(c=0;c<A.length;c++){var L=A[c],K=void 0;c>0&&(F=!0);let m;L.nodeType===1&&(m=L);if(m&&m.tagName==="s"){if((L=(L=m.getAttribute("p"))?this.pens[L]:null)&&
L.gi&&(L.gi===1?(L=A.slice(c,c+4),L.length===4&&(K=M4n(b,H,z,F,W,L,this.pens),c+=3)):K=M4n(b,H,z,F,W,[m],this.pens)),!K){var D=m;K=b;L=H;var P=z,M=F;let S=D.textContent?D.textContent:"";var f=D.getAttribute("p");f=f?this.pens[f]:null;D=lM(D,"t")||0;K=new j1(K+D,L-D,W,P,S,M,f)}}else K=new j1(b,H,W,z,L.textContent||"",F,r);N.push(K);this.D=K}if(N.length>0){N[0].windowId===this.G&&(this.O=qRU(this,U,C,!0),h.push(this.O));for(let m of N)m.windowId=this.O.id,this.O.O.push(m),h.push(m)}}var U=h}else U=
[];return U}};var Bll=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),jvO=class extends bZ{constructor(b){super();this.Z=b;this.O=new Map;this.N=new Map;this.G=new Map;this.D=new Map}reset(){this.D.clear()}A(b,C){b=JSON.parse(b);if(!b)return[];if(b.pens){var F=b.pens,z=0;for(var N of F){F={};var h=N.pParentId;h&&Object.assign(F,this.O.get(h));N.bAttr&&(F.bold=!0);N.iAttr&&(F.italic=!0);N.uAttr&&(F.underline=!0);h=N.ofOffset;h!=null&&(F.offset=h);N.szPenSize!==void 0&&(F.fontSizeIncrement=N.szPenSize/100-1);
h=N.etEdgeType;h!=null&&(F.charEdgeStyle=h);N.ecEdgeColor!==void 0&&(F.tX=O3(N.ecEdgeColor));h=N.fsFontStyle;h!=null&&h!==0&&(F.fontFamily=h);N.fcForeColor!==void 0&&(F.color=O3(N.fcForeColor));N.foForeAlpha!==void 0&&(F.textOpacity=N.foForeAlpha/255);N.bcBackColor!==void 0&&(F.background=O3(N.bcBackColor));N.boBackAlpha!==void 0&&(F.backgroundOpacity=N.boBackAlpha/255);(h=N.rbRuby)&&h!==10&&(F.gi=h>10?h-1:h,F.textEmphasis=Bll.get(F.gi));N.hgHorizGroup&&(F.a5=N.hgHorizGroup);this.O.set(z++,F)}}if(b.wsWinStyles){z=
b.wsWinStyles;N=0;for(var H of z)z={},(F=H.wsParentId)?Object.assign(z,this.G.get(F)):Object.assign(z,this.Z),H.mhModeHint!==void 0&&(z.DN=H.mhModeHint),H.juJustifCode!==void 0&&(z.textAlign=H.juJustifCode),H.pdPrintDir!==void 0&&(z.Gi=H.pdPrintDir),H.sdScrollDir!==void 0&&(z.Mi=H.sdScrollDir),H.wfcWinFillColor!==void 0&&(z.windowColor=O3(H.wfcWinFillColor)),H.wfoWinFillAlpha!==void 0&&(z.windowOpacity=H.wfoWinFillAlpha/255),this.G.set(N++,z)}if(b.wpWinPositions){N=b.wpWinPositions;H=0;for(var c of N)N=
{},(z=c.wpParentId)&&Object.assign(N,this.N.get(z)),c.ahHorPos!==void 0&&(N.gO=c.ahHorPos),c.apPoint!==void 0&&(N.Y4=c.apPoint),c.avVerPos!==void 0&&(N.vx=c.avVerPos),c.ccCols!==void 0&&(N.u5=c.ccCols),c.rcRows!==void 0&&(N.nK=c.rcRows),this.N.set(H++,N)}if(b.events){b=b.events;c=[];for(let t of b)if(H=(t.tStartMs||0)+C,N=t.dDurationMs||0,t.id)z=String(t.id),b=siU(this,t,H,N,z),c.push(b),this.D.set(z,b);else{t.wWinId?z=t.wWinId.toString():(z="_"+fv++,b=siU(this,t,H,N,z),c.push(b),this.D.set(z,b));
b=c;var r=t;N===0&&(N=5E3);F=this.D.get(z);let Fn=(h=!!r.aAppend)?6:5,Pu=r.segs,lj=null;r.pPenId&&(lj=this.O.get(r.pPenId));for(r=0;r<Pu.length;r++){var L=Pu[r],K=L.utf8;if(K){var D=L.tOffsetMs||0;let $d=null;L.pPenId&&($d=this.O.get(L.pPenId));if((F.params.DN!=null?F.params.DN:F.O.length>1?1:0)===2&&h&&K==="\n")continue;L=null;var P=[],M;if(M=$d&&$d.gi===1)a:{M=Pu;var f=r;if(f+3>=M.length||!M[f+1].pPenId||!M[f+2].pPenId||!M[f+3].pPenId){M=!1;break a}var U=M[f+1].pPenId;(U=this.O.get(U))&&U.gi&&U.gi===
2?(U=M[f+2].pPenId,U=this.O.get(U),!U||!U.gi||U.gi<3?M=!1:(U=M[f+3].pPenId,M=(U=this.O.get(U))&&U.gi&&U.gi===2?!0:!1)):M=!1}if(M)D=Pu[r+1].utf8,L=Pu[r+3].utf8,M=Pu[r+2].utf8,f=this.O.get(Pu[r+2].pPenId),K=DAl(K,D,M,L,f),L=new j1(H,N,Fn,z,K,h,$d),r+=3;else{if(K.indexOf("<")>-1){P=$d;M=lj;f=H;U=N;var W=D,A=Fn,m=h;let SY=[];var S=g.a2(`<html>${K}</html>`);if(!S.getElementsByTagName("parsererror").length&&S.firstChild?.childNodes.length)for(let Gj of S.firstChild.childNodes){S=Gj.textContent?.replace(/\n/g,
"")??"";if(Gj.nodeType===3&&(!S||S.match(/^ *$/)!=null))continue;let Nt={};Object.assign(Nt,P||M);switch(Gj?.tagName){case "b":Nt.bold=!0;break;case "i":Nt.italic=!0;break;case "u":Nt.underline=!0}SY.push(new j1(f+W,U-W,A,F.id,S,m,Nt))}P=SY}P.length||(P=[new j1(H+D,N-D,Fn,F.id,K,h,$d||lj)])}if(P.length)for(let SY of P)b.push(SY),F.O.push(SY);else L&&(b.push(L),F.O.push(L))}h=!0}}C=c}else C=[];return C}};var fMl=class extends g.va{constructor(b,C,F){super(b);this.videoData=C;this.audioTrack=F;this.W=C.T6}N(b,C,F){UXs(this.videoData.videoId,b.vssId,F.oV)}G(b){if(this.audioTrack)for(let C of this.audioTrack.captionTracks)g.b2(this.O,C);b.GP()}};var hrB=class extends GG{constructor(b,C,F,z,N,h,H,c,r,L){super(b,C,F,z,N,h,H,c,r,L);this.type=1}rI(b){var C=this.D.O;super.rI(b);for(b=b.length;b<C.length;b++){let N=C[b],h;if(z&&N.O===F)h=z;else{h={};Object.assign(h,N.O);Object.assign(h,$qV);var F=N.O;var z=h}CG3(this,N,h)}}},$qV={P0:!0};var Bu5=class extends qqs{constructor(b,C){super();this.trackData=b;this.Z=C;this.version=this.G=this.A=this.byteOffset=0;this.D=[];this.O=new DataView(this.trackData)}N(b,C,F,z,N){if(F<z){let h="_"+fv++;F=F/1E3-this.Z;z=z/1E3-this.Z;b=new $b(F,z-F,5,h,{textAlign:0,Y4:0,gO:C*2.5,vx:b*5.33});N=new j1(F,z-F,5,h,N);this.D.push(b);this.D.push(N)}}},lMV=class extends bZ{constructor(b,C){super();this.D=b;this.N=C;this.track=this.N.languageName==="CC3"?4:0;this.O=new Dq7;this.O.D=1<<this.track}A(b){b=new Bu5(b,
this.D);if(jiV(b)){for(;b.byteOffset<b.O.byteLength;)for(b.version===0?b.A=xb(b)*(1E3/45):b.version===1&&(b.A=xb(b)*4294967296+xb(b)),b.G=TG(b);b.G>0;b.G--){var C=TG(b);let F=TG(b),z=TG(b);C&4&&(C&3)===this.track&&(this.track===0||this.track===1)&&(C=this.O,C.O.push({time:b.A,type:this.track,rA:F,UL:z,order:C.O.length}))}HFs(this.O,b);return b.D}return[]}reset(){this.O.clear()}};var HJs=class extends GG{constructor(b,C,F,z,N,h,H,c,r,L){super(b,C,F,z,N,h,H,c,r,L);this.type=2;this.tA=[];this.AA=this.DQ=this.hA=0;this.ej=NaN;this.CX=0;this.D1=null;this.SB=new g.D5(this.QD,433,this);this.Z&&(L.createClientVe(this.Z,this,167342),this.Y(this.Z,"click",()=>{L.logClick(this.Z)}),b=new g.W8(this.element,!0),g.R(this,b),b.subscribe("hoverstart",()=>{L.logVisibility(this.Z,!0)},this));
g.jQ(this.element,"ytp-caption-window-rollup");g.R(this,this.SB);g.xO(this.element,"overflow","hidden")}wR(){g.pn(this.SB)}QD(){this.element.removeEventListener("transitionend",this.QD,!1);g.$k(this.element,"ytp-rollup-mode");this.B(this.D1,!0)}hf(){return this.N?this.AA:this.DQ}MN(){return this.N?this.DQ:this.AA}B(b,C){this.D1=b;if(this.D.params.nK){var F=0;for(let z=0;z<this.K.length&&F<b.length;z++)this.K[z]===b[F]&&F++;F>0&&F<b.length&&(b=this.K.concat(b.slice(F)));this.CX=this.AA;this.DQ=this.AA=
0;super.B(b);kl3(this,C)}super.B(b)}};var kBT=class{constructor(b,C,F,z){this.X=b;this.G=C;this.logger=F;this.mD=z;this.xw=[];this.O=null;this.A=[];this.XG=[];this.D=null;this.jB={HUA:()=>this.D,
RR:()=>this.xw,
FbD:N=>{this.A=N},
QYv:()=>this.A};
b=g.js(this.X.U().experiments,"html5_override_micro_discontinuities_threshold_ms");this.N=b>0?b:10}unload(){this.D!=null&&(this.X.removeEventListener("sabrCaptionsDataLoaded",this.D),this.D=null);this.xw=[];this.O=null;this.A=[];this.X.publish("sabrCaptionsBufferedRangesUpdated",this.xw)}mf(b){return{formatId:g.da(b.info.JA.info,this.mD),vv:b.info.vv+(this.mD?0:1),startTimeMs:b.info.N*1E3,durationMs:b.info.K*1E3}}};var iJ7=class extends g.va{constructor(b,C){super(C);this.D=b;this.X=C;this.logger=new g.zh("caps");this.B=this.AA=null;this.lB=new kBT(this.X,this,this.logger,this.D.mD)}N(b,C,F){this.A();C=b.getId();C=C!=null&&C in this.D.O?this.D.O[C]:null;C||(C=b.languageCode,C=this.D.isManifestless?XW5(this,C,"386"):XW5(this,C));C&&(this.B=b,this.AA=C,Tul(this.lB,F),this.X.publish("sabrCaptionsTrackChanged",g.da(C.info,this.D.mD)))}G(b){var C=this.D.isManifestless?WoT(this,"386"):WoT(this);for(let F of C)g.b2(this.O,
F);b.GP()}A(){this.B&&(this.B=this.AA=null,this.lB.unload(),this.X.publish("sabrCaptionsTrackChanged",null))}Z(){return""}};var emn="WEBVTT".split("").map(b=>b.charCodeAt(0)),mAn=class extends bZ{constructor(){super()}A(b,C){b instanceof ArrayBuffer&&(b=g.gz(new Uint8Array(b)));
var F=[];b=b.split(oJV);for(let f=1;f<b.length;f++){var z=b[f],N=C;if(z!==""&&!y1T.test(z)){var h=Ck.exec(z);if(h&&h.length>=4){var H=X5(h[1]),c=X5(h[2])-H;H+=N;var r=(h=h[3])?h.split(" "):[];h={};var L=null;var K="";var D=null,P="";for(let U of r){r=U.split(":");if(r.length!==2)continue;var M=r[1];switch(r[0]){case "line":r=M.split(",");r[0].endsWith("%")&&(L=r[0],h.vx=Number.parseInt(L,10),r.length===2&&(K=r[1].trim()));break;case "position":r=M.split(",");D=r[0];h.gO=Number.parseInt(D,10);r.length===
2&&(P=r[1].trim());break;case "align":switch(M){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}L||K||(K="end");if(!D)switch(h.textAlign){case 0:h.gO=0;break;case 1:h.gO=100;break;case 2:h.gO=50}if(h.textAlign!=null){L=0;switch(K){case "center":L+=3;break;case "end":L+=6;break;default:L+=0}switch(P){case "line-left":L+=0;break;case "center":L+=1;break;case "line-right":L+=2;break;default:switch(h.textAlign){case 0:L+=0;break;case 2:L+=1;break;case 1:L+=
2}}K=L<0||L>8?7:L;h.Y4=K}z=z.substring(Ck.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");P=h;h={};if(z.indexOf("<")<0&&z.indexOf("&")<0)N=Rm5(H,c,5,P),H=new j1(H,c,5,N.id,z,!1,g.vs(h)?void 0:h),F.push(N),F.push(H),N.O.push(H);else for(K=z.split(OJB),K.length===1?(z=5,P=Rm5(H,c,z,P)):(L=z=6,P=Object.assign({u5:32},P),P=new $b(H,c,L,"_"+fv++,P)),F.push(P),L=H,D=0;D<K.length;D++)if(r=K[D],D%2===0){M=g.a2(`<html>${r}</html>`);let U;M.getElementsByTagName("parsererror").length?(U=M.createElement("span"),
U.appendChild(M.createTextNode(r))):U=M.firstChild;v5y(this,L,c-(L-H),z,P,D>0,U,h,F)}else L=X5(r)+N}Ck.lastIndex=0}}return F}},y1T=/^NOTE/,oJV=/(?:\r\n|\r|\n){2,}/,Ck=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),OJB=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var Tln=class extends g.pu{constructor(b,C){super();this.X=b;this.V=C;this.O=null;this.Bw=this.X.R4();this.logger=new g.zh("caps")}clear(){this.O&&this.O.dispose();this.O=null}reset(){this.O&&this.O.reset()}GD(){super.GD();this.clear()}};var wW5={windowColor:"#080808",windowOpacity:0,textAlign:2,Y4:7,gO:50,vx:100,isDefault:!0,JM:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},ZFb={windowColor:"#080808",windowOpacity:0,textAlign:0,Y4:7,gO:50,vx:100,isDefault:!0,JM:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.QR("captions",class extends g.Ro{constructor(b){super(b);this.X=b;this.ej=[];this.NT={};this.LJ={};this.K=!1;this.A="NONE";this.O=this.W=this.lB=this.hA=this.xf=null;this.qT={GP:()=>{this.GP()},
oV:(z,N,h,H,c=0)=>{var r=Number(this.videoData.U().wI().O.iB(g.WAj)??0);c>0&&r>0&&this.videoData.lengthSeconds>0&&c/this.videoData.lengthSeconds>r?this.X.FS("tts",{dropcap:c}):this.oV(z,N,h,H)}};
this.D=null;this.V=this.X.U();this.videoData=this.X.getVideoData();this.QD=this.X.VD();this.G={JM:{}};this.Z={JM:{}};this.videoData.KX()?this.A="OFFLINE":g.oSn(this.videoData,this.X)?this.A="HLS":xAn(this.videoData,this.X)?this.A="SABR_LIVE":g.yRA(this.videoData,this.X)?this.A="LIVE":this.videoData.captionTracks.length?this.A="INNERTUBE":this.videoData.Et&&(this.A="TTS");this.ZQ=this.V.controlsType==="3";this.rI=new Tln(this.X,this.V);this.tA=new g.d7(this);this.B=new g.Q({J:"div",L:"ytp-caption-window-container",
S:{id:"ytp-caption-window-container"}});this.AA={top:0,right:0,bottom:0,left:0,width:1,height:1};var C=null,F=g.Qz("yt-html5-player-modules::subtitlesModuleData");F&&(C=new g.SQ(F));this.storage=C;C=b.Yn();this.lS=!!C?.KJ();this.Hv=!!C?.hA();this.N=WH(this);this.DQ=ugO(this);g.R(this,this.rI);this.N?this.KJ=this.XS=null:(this.XS=new g.Kn(this.KX,void 0,this),g.R(this,this.XS),this.KJ=new g.D5(this.wR,2E3,this),g.R(this,this.KJ));g.R(this,this.tA);g.O4(this.player,this.B.element,4);g.R(this,this.B);
this.N||this.tA.Y(b,"resize",this.cv);C=g.Az(this.V)&&!g.pt()&&!this.X.isFullscreen();F=this.V.wI().O.iB(g.cvn)&&g.$e(this.V)&&g.yV;(this.GK=(C||F)&&!this.N&&!this.DQ)&&this.tA.Y(b,C?"resize":"fullscreentoggled",this.MN);this.tA.Y(b,"onPlaybackAudioChange",this.hf);this.tA.Y(b,g.mw("captions"),z=>{this.onCueRangeEnter(z)});
this.tA.Y(b,g.S7("captions"),z=>{this.onCueRangeExit(z)});
e1(this,Dz()||{});g.LB(this.player,"onCaptionsModuleAvailable");this.A==="HLS"&&this.N&&(b=this.X.Yn().kw(),this.Hv&&this.tA.Y(b.textTracks,"addtrack",this.CX))}GD(){if(this.N||this.DQ){let b=this.X.Yn();b&&!b.gI()&&b.K()}else U3(this,!1);super.GD()}aD(){return this.V.C("html5_honor_caption_availabilities_in_audio_track")&&this.A!=="LIVE"&&this.A!=="SABR_LIVE"}gN(){if(this.ZQ)return this.N||this.DQ;if(this.A==="HLS")return this.N;var b=this.getAudioTrack();if(this.aD()){if(!b.captionTracks.length)return!1;
if(!this.O)return!0}b=gE(b,g.FH(this.V));return b==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:b==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?S1(this):mO(this)||S1(this)?!0:Glb(this)}load(){super.load();this.W=this.getAudioTrack();if(this.O)this.D&&(this.rI.clear(),this.N?QiB(this,!0):this.player.getPresentingPlayerType()!==3&&this.O.N(this.D,"json3",this.qT),this.A!=="HLS"&&this.N||this.DQ||aD(this)||g.LB(this.player,"captionschanged",g.vp(this.D)));else{let b;this.A==="OFFLINE"?b=new fMl(this.player,this.videoData,
this.getAudioTrack()):this.A==="SABR_LIVE"?b=new iJ7(this.videoData.O,this.player):this.A==="HLS"?b=new LmO(this.player):this.A==="LIVE"?b=new Vzn(this.videoData.O,this.player):this.A==="INNERTUBE"?b=new g.Aw(this.player,this.videoData,this.getAudioTrack()):b=new g.Jw(this.player,this.videoData.Et,this.videoData.videoId,g.I6u(this.videoData),this.videoData.Pt,this.videoData.eventId);this.O=b;g.R(this,this.O);this.O.G(this.qT)}}unload(){this.N&&this.D?QiB(this,!1):(this.KJ&&this.KJ.Ef(),this.player.gw("captions"),
this.ej=[],this.O&&this.O.A(),this.rI.clear(),this.lB&&this.player.Vw(this.lB),this.cv());super.unload();this.player.W3();g.LB(this.player,"captionschanged",{})}create(){this.gN()&&this.load();var b;a:{if(this.V.C("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(b=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(let C of b)if(C.kind==="asr"&&C.languageCode===
"en"){b=!0;break a}b=!1}b&&this.X.publish("showpromotooltip",this.B.element)}GP(){var b=gE(this.player.getAudioTrack(),g.FH(this.V));var C=b==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?Zz(this,this.K):b==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&S1(this)?uM(this):mO(this)||this.K||Glb(this)?Zz(this,this.K):S1(this)?uM(this):null;if(this.A!=="HLS"&&this.N||this.DQ){let F=g.xP(this.O.O,!0);b=[];for(let z=0;z<F.length;z++){let N=F[z],h=g.Nv("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",
g.Rh(N));h.setAttribute("srclang",g.AL(N));h.setAttribute("id",N.toString());this.DQ||h.setAttribute("src",this.O.Z(N,"vtt"));N===C&&h.setAttribute("default","1");b.push(h)}C=this.X.Yn();C.lB(b);b=C.kw();this.Hv&&this.tA.Y(b.textTracks,"change",this.Ww)}else!this.D&&C&&ID(this,C),g.LB(this.player,"onCaptionsTrackListChanged"),g.Yu(this.player,"onApiChange")}getTrackById(b){var C=g.xP(this.O.O,!0);for(let F=0;F<C.length;F++)if(C[F].toString()===b)return C[F];return null}Ww(){var b=this.X.Yn().kw().textTracks,
C=null;for(let F=0;F<b.length;F++)b[F].mode==="showing"&&(C=this.getTrackById(b[F].id));(this.loaded?this.D:null)!==C&&ID(this,C,!0)}CX(){this.O?.G(this.qT)}yj(){!this.D&&this.N||this.unload()}oV(b,C,F,z){if(b){tZ(this,this.D??void 0);this.O.DQ()&&(this.ej=[],this.X.gw("captions"),VZ(this.XS),this.rI.reset());a:{var N=this.rI;z=z||0;F=JQl(N,b,F||0);b=[];try{for(let A of F){let m=A.trackData,S=A.gU,t=N.V.C("safari_live_drm_captions_fix");if(typeof m!=="string"){F=b;var h=F.concat;if(t&&UAT(m))var H=
SRb(N,m,S);else{var c=N,r=C,L=m,K=S,D=z;if(!fFy(L))throw Error("Invalid binary caption track data");c.O||(c.O=new lMV(D,r));H=c.O.A(L,K)}var P=h.call(F,H)}else{if(m.substring(0,6)==="WEBVTT")var M=b.concat(SRb(N,m,S));else{F=b;var f=F.concat;b:{r=N;c=C;if(m[0]==="{")try{r.O||(r.O=new jvO(aF3(c)));var U=r.O.A(m,S);break b}catch(lj){g.ba(lj);U=[];break b}let Fn=g.a2(m);if(!Fn||!Fn.firstChild){let lj=Error("Invalid caption track data");lj.params=m;throw lj;}if(Fn.firstChild.tagName==="timedtext"){if(Number(Fn.firstChild.getAttribute("format"))===
3){L=Fn;r.O||(r.O=new svB(aF3(c)));U=r.O.A(L,S);break b}let lj=Error("Unsupported subtitles format in web player (Format2)");lj.params=m;throw lj;}if(Fn.firstChild.tagName==="transcript"){let lj=Error("Unsupported subtitles format in web player (Format1)");lj.params=m;throw lj;}let Pu=Error("Invalid caption track data");Pu.params=m;throw Pu;}M=f.call(F,U)}P=M}b=P}var W=b;break a}catch(A){g.N8(N.logger,187101178,`Captions parsing failed: ${A.message}. `);N.clear();W=[];break a}W=void 0}this.V.C("html5_sabr_live_support_subfragmented_captions")&&
this.O instanceof iJ7&&(C=this.O.lB,N=[],W.length>0&&(N=W.slice(C.A.length)),C.A=!C.O||C.O.info.Zx?[]:W,W=N);W.length>0&&(C=this.D,this.Mv(C,!!C,aD(this)?"g":this.K?"m":"s"));this.player.Vw(W,void 0,this.A==="LIVE"||this.A==="SABR_LIVE");!this.K||this.DQ||aD(this)||g.fP(this.V)||g.vK(this.V)||g.jb(this.V)||this.V.tA==="shortspage"||this.player.isInline()||(this.KJ.Ef(),W=pWO({Y4:0,gO:5,vx:5,nK:2,textAlign:0,Gi:0,lang:"en"}),this.hA=[W],C=["Click "," for settings"],this.xf||(N=new g.XK(g.GJ()),g.R(this,
N),this.xf=N.element),N=W.end-W.start,(P=g.Rh(this.D))&&this.hA.push(new j1(W.start,N,0,W.id,P)),this.hA.push(new j1(W.start,N,0,W.id,C[0]),new j1(W.start,N,0,W.id,this.xf,!0),new j1(W.start,N,0,W.id,C[1],!0)),this.player.Vw(this.hA),g.M2(this.KJ));!this.K||this.DQ||aD(this)||(this.V.C("enable_player_captions_persistence_state_machine")?JZ(this,!0):g.FH(this.V)?wE(this,!0):E3(this,!0),this.W&&(this.W.N=this.D),this.player.W3());this.K=!1}}onCueRangeEnter(b){this.ej.push(b);VZ(this.XS)}onCueRangeExit(b){g.z3(this.ej,
b);this.O instanceof Vzn&&this.O.AA&&this.player.l_([b]);VZ(this.XS)}getCaptionWindowContainerId(){return this.B.element.id}wR(){E5V(this,this.hA);this.hA=null}KX(){if(!this.GK||!this.N){this.XS.stop();g.An(this.LJ);this.ej.sort(g.Jl);var b=this.ej;if(this.lB){let C=g.mI(b,function(F){return this.lB.indexOf(F)===-1},this);
C.length&&(b=C)}for(let C of b)C instanceof $b?Fmn(this,C):zrT(this,C);for(let [C,F]of Object.entries(this.NT)){let z=C,N=F;this.LJ[z]?(N.element.parentNode||(N instanceof HJs||N instanceof hrB||g.kB(this.NT,(h,H)=>{H!==z&&h.D.params.Y4===N.D.params.Y4&&h.D.params.gO===N.D.params.gO&&h.D.params.vx===N.D.params.vx&&(h.dispose(),delete this.NT[H]);return H===z},this),this.B.element.appendChild(N.element)),N.B(this.LJ[z])):(N.dispose(),delete this.NT[z])}}}GW(){e1(this,{},!0);
g.LB(this.player,"captionssettingschanged")}GU(){var b=this.V.C("enable_player_captions_new_style_defaults")?ZFb:wW5,C=b.JM;b={background:C.background,backgroundOpacity:C.backgroundOpacity,charEdgeStyle:C.charEdgeStyle,color:C.color,fontFamily:C.fontFamily,fontSizeIncrement:C.fontSizeIncrement,fontStyle:C.bold&&C.italic?3:C.bold?1:C.italic?2:0,textOpacity:C.textOpacity,windowColor:b.windowColor,windowOpacity:b.windowOpacity};C=Dz()||{};C.background!=null&&(b.background=C.background);C.backgroundOverride!=
null&&(b.backgroundOverride=C.backgroundOverride);C.backgroundOpacity!=null&&(b.backgroundOpacity=C.backgroundOpacity);C.backgroundOpacityOverride!=null&&(b.backgroundOpacityOverride=C.backgroundOpacityOverride);C.charEdgeStyle!=null&&(b.charEdgeStyle=C.charEdgeStyle);C.charEdgeStyleOverride!=null&&(b.charEdgeStyleOverride=C.charEdgeStyleOverride);C.color!=null&&(b.color=C.color);C.colorOverride!=null&&(b.colorOverride=C.colorOverride);C.fontFamily!=null&&(b.fontFamily=C.fontFamily);C.fontFamilyOverride!=
null&&(b.fontFamilyOverride=C.fontFamilyOverride);C.fontSizeIncrement!=null&&(b.fontSizeIncrement=C.fontSizeIncrement);C.fontSizeIncrementOverride!=null&&(b.fontSizeIncrementOverride=C.fontSizeIncrementOverride);C.fontStyle!=null&&(b.fontStyle=C.fontStyle);C.fontStyleOverride!=null&&(b.fontStyleOverride=C.fontStyleOverride);C.textOpacity!=null&&(b.textOpacity=C.textOpacity);C.textOpacityOverride!=null&&(b.textOpacityOverride=C.textOpacityOverride);C.windowColor!=null&&(b.windowColor=C.windowColor);
C.windowColorOverride!=null&&(b.windowColorOverride=C.windowColorOverride);C.windowOpacity!=null&&(b.windowOpacity=C.windowOpacity);C.windowOpacityOverride!=null&&(b.windowOpacityOverride=C.windowOpacityOverride);return b}Jb(b,C){var F={};Object.assign(F,Dz());Object.assign(F,b);e1(this,F,C);g.LB(this.player,"captionssettingschanged")}cv(){!this.N&&this.loaded&&(g.fb(this.NT,function(b,C){b.dispose();delete this.NT[C]},this),this.KX())}KU(b,C){switch(b){case "fontSize":if(isNaN(C))break;
b=g.f_(C,-2,4);this.Jb({fontSizeIncrement:b});return b;case "reload":C&&!this.N&&ID(this,this.D,!0);break;case "stickyLoading":C!==void 0&&this.V.lB&&(this.V.C("enable_player_captions_persistence_state_machine")?JZ(this,!(!C||!C.userInitiated)):g.FH(this.V)?wE(this,!!C):E3(this,!!C));break;case "track":return c17(this,C);case "tracklist":return this.O?g.aO(g.xP(this.O.O,!(!C||!C.includeAsr)),F=>g.vp(F)):[];
case "translationLanguages":return this.O?this.O.W.map(F=>Object.assign({},F)):[];
case "sampleSubtitles":this.N||C===void 0||U3(this,!!C);break;case "sampleSubtitlesCustomized":this.N||U3(this,!!C,C);break;case "recommendedTranslationLanguages":return g.y0();case "defaultTranslationSourceTrackIndices":return this.O?this.O.NT:[]}}getOptions(){var b="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.V.lB&&b.push("stickyLoading");return b}wg(){var b=this.D;if(this.X.A1("captions")){if(this.V.C("html5_modify_caption_vss_logging"))return(b=this.videoData.b$??
null)?{cc:g.GWj(b)}:{};if(b){let C=b.vssId;b.translationLanguage&&C&&(C=`t${C}.${g.AL(b)}`);return{cc:C}}}return{}}WA(b){this.isSubtitlesOn()?(this.V.C("enable_player_captions_persistence_state_machine")&&b?JZ(this,!1):g.FH(this.V)?wE(this,!1):E3(this,!1),tZ(this),ID(this,null,!0)):this.SO(b)}SO(b){var C=aD(this)||!this.D?Zz(this,!0):this.D;C&&this.pZ(C.vssId,"m");this.isSubtitlesOn()||ID(this,C,this.V.C("enable_player_captions_persistence_state_machine")?b:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.D&&!aD(this)}hf(){var b=aD(this);S1(this,b)?ID(this,this.getAudioTrack().O,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.aD()&&(this.K=!1,this.D=null,this.O&&(this.O.dispose(),this.O=null)),this.gN()&&(b?ID(this,Zz(this,!1),!1):this.load()))}hk(b){b&&(this.AA={top:b.top,right:b.right,bottom:b.bottom,left:b.left,width:1-b.left-b.right,height:1-b.top-b.bottom},this.B.element.style.top=`${this.AA.top*100}%`,this.B.element.style.left=`${this.AA.left*100}%`,this.B.element.style.width=
`${this.AA.width*100}%`,this.B.element.style.height=`${this.AA.height*100}%`,this.B.element.style.position="absolute",b=NlT(this))&&(this.B.element.style.width=`${b.width}px`,this.B.element.style.height=`${b.height}px`)}onVideoDataChange(b,C){b==="newdata"&&(this.videoData=C,this.loaded&&this.unload(),this.K=!1,this.D=null,this.O&&(this.O.dispose(),this.O=null,g.LB(this.player,"captionschanged",{})),this.gN()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}MN(){if(this.V.wI().O.iB(g.cvn)){if(this.loaded&&
this.unload(),this.ZQ=this.X.isFullscreen()||this.V.controlsType==="3",this.N=WH(this),this.DQ=ugO(this),this.N||this.DQ){var b=this.X.Yn();b&&!b.gI()&&b.K();this.GP()}}else(b=this.X.Yn())&&!b.gI()&&b.K(),this.X.isFullscreen()?(this.N=this.ZQ=!0,this.loaded&&this.GP()):(this.ZQ=this.V.controlsType==="3",this.N=WH(this));ID(this,this.D)}Et(){var b=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;b&&g.hT(this.player,"innertubeCommand",b)}Mv(b,C,F){var z=
/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,N="";b&&(N=b.vssId,N=N.replace(z,""));var h="";b&&b.getId()&&(h=b.getId()||"");b&&b.getXtags()&&(b=b.getXtags(),b=b.replace(z,""),h=h.concat(`;${b}`));this.A==="HLS"&&(h="");this.X.Mv(C?N:"",C?h:"",F)}pZ(b,C){b=(b||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");b.length>0&&this.X.pZ(b,C)}});})(_yt_player);
