(function(g){var window=this;'use strict';var F33=function(b,C){g.hT(b,"onAutonavCoundownStarted",C)},zSB=function(b){return b.isBackground()&&b.Ez()},Np5=function(b,C){C=C.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.nextButton?.buttonRenderer;
b.DQ=C?.navigationEndpoint;C=C?.trackingParams;b.playButton&&C&&b.X.setTrackingParams(b.playButton.element,C)},Vv=function(b){var C=Y8(b),F=Math,z=F.min;
var N=b.K?Date.now()-b.K:0;F=z.call(F,N,C);nk(b,Math.ceil((C-F)/1E3));C-F<=500&&b.O()?b.select(!0):b.O()&&b.B.start()},gO=function(b){var C=b.X.D3(!0,b.X.isFullscreen());
g.kk(b.container.element,"ytp-autonav-endscreen-small-mode",b.ue(C));g.kk(b.container.element,"ytp-autonav-endscreen-is-premium",!!b.suggestion&&!!b.suggestion.oG);g.kk(b.X.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!b.X.S3());g.kk(b.X.getRootNode(),"countdown-running",b.O());g.kk(b.container.element,"ytp-player-content",b.X.S3());b.X.C("web_post_play_autonav_embiggening")||g.xO(b.overlay.element,{width:`${C.width}px`});if(b.X.C("web_post_play_autonav_embiggening")){var F=b.X.getRootNode().getBoundingClientRect();
C=Math.min(720,F.width*.5);var z=C*.5625;F=F.height-36-60;z>F&&(z=F,C=16/9*z);g.xO(b.D.pJ("ytp-autonav-endscreen-upnext-thumbnail"),{height:`${z}px`,width:`${C}px`});g.xO(b.container.element,{width:`${C}px`})}b.O()||(b.X.S3()?nk(b,Math.round(Y8(b)/1E3)):nk(b),C=!!b.suggestion&&!!b.suggestion.jo,z=b.X.getVideoData(),z=z?.autonavState===1&&z?.CF&&b.X.S3()?!1:b.X.S3()||!(b.suggestion&&b.suggestion.jo),g.kk(b.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!z&&C),g.kk(b.container.element,
"ytp-autonav-endscreen-upnext-no-alternative-header",z&&!C),b.Z.fX(b.X.S3()))},nk=function(b,C=-1){b=b.D.pJ("ytp-autonav-endscreen-upnext-header");
g.cB(b);if(C>=0){C=String(C);let z="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],N="Up next in $SECONDS".indexOf(z);if(N>=0){var F=g.h8("Up next in $SECONDS".slice(0,N));b.appendChild(F);F=g.Nv("span");g.q2(F,"ytp-autonav-endscreen-upnext-header-countdown-number");g.nC(F,C);b.appendChild(F);C=g.h8("Up next in $SECONDS".slice(N+z.length));b.appendChild(C);return}}g.nC(b,"Up next")},Y8=function(b){return b.X.isFullscreen()?(b=b.X.getVideoData()?.tC,b===-1||b===void 0?8E3:b):b.X.a4()>=0?
b.X.a4():g.js(b.X.U().experiments,"autoplay_time")||1E4},Kk=function(b,C){C=hSl(b,C);
var F=Math,z=F.min;var N=(0,g.u)()-b.K;F=z.call(F,N,C);C=C===0?1:Math.min(F/C,1);b.ej.setAttribute("stroke-dashoffset",`${-211*(C+1)}`);C>=1&&b.O()&&!b.isCasting()?b.select(!0):b.O()&&b.D.start()},hSl=function(b,C){return C?C:b.api.isFullscreen()?(b=b.api.getVideoData()?.tC,b===-1||b===void 0?8E3:b):b.api.a4()>=0?b.api.a4():g.js(b.api.U().experiments,"autoplay_time")||1E4},Db=function(b){return g.T0(b.player)&&b.B()&&!b.N},ME=function(b){var C=b.S3();
C!==b.W&&(b.W=C,b.player.publish("autonavvisibility"))},pk=function(b){return g.T0(b.player)&&b.B()&&!b.G},dO=function(b){var C=b.S3();
C!==b.AA&&(b.AA=C,b.player.publish("autonavvisibility"))},HS7=function(b){b=b.U();
return b.ER&&!b.disableOrganicUi},c2V=function(b){var C=b.player.getVideoData();
if(!C||b.O===C.hf)return!1;b.O=C.hf;return!0},r2s=function(b){b.player.gw("endscreen");
var C=b.player.getVideoData();C=new g.mR(Math.max((C.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var F=new g.mR(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});b.player.Vw([C,F])};
g.Dk.prototype.a4=g.Nm(15,function(){return this.app.a4()});
g.zV.prototype.a4=g.Nm(14,function(){return this.getVideoData().YA});
g.Kw.prototype.qe=g.Nm(13,function(b){this.i_().qe(b)});
g.IW.prototype.qe=g.Nm(12,function(b){this.ym!==b&&(this.ym=b,this.aM())});
var PN=class extends g.Q{constructor(b){super({J:"div",L:"ytp-autonav-endscreen-countdown-overlay"});this.cancelCommand=this.DQ=void 0;this.K=0;b.C("web_post_play_autonav_embiggening")&&g.jQ(this.element,"ytp-autonav-endscreen-upnext-updated");this.container=new g.Q({J:"div",L:"ytp-autonav-endscreen-countdown-container"});g.R(this,this.container);this.container.oA(this.element);var C=b.U(),F=C.N;this.X=b;this.suggestion=null;this.onVideoDataChange("newdata",this.X.getVideoData());this.Y(b,"videodatachange",
this.onVideoDataChange);this.D=new g.Q({J:"div",L:"ytp-autonav-endscreen-upnext-container",S:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},j:[{J:"div",L:"ytp-autonav-endscreen-topbar-container",j:[{J:"div",L:"ytp-autonav-endscreen-upnext-header"},{J:"div",L:"ytp-autonav-endscreen-upnext-alternative-header",yD:"{{autoplayAlternativeHeader}}"}]},{J:"a",L:"ytp-autonav-endscreen-link-container",
S:{href:"{{url}}",target:F?C.AA:""},j:[{J:"div",L:"ytp-autonav-endscreen-upnext-thumbnail",S:{style:"{{background}}"},j:[{J:"div",S:{"aria-label":"{{timestamp}}"},aA:["ytp-autonav-timestamp"],yD:"{{duration}}"},{J:"div",aA:["ytp-autonav-live-stamp"],yD:"Live"},{J:"div",aA:["ytp-autonav-upcoming-stamp"],yD:"Upcoming"}]},{J:"div",L:"ytp-autonav-endscreen-video-info",j:[{J:"div",L:"ytp-autonav-endscreen-premium-badge"},{J:"div",L:"ytp-autonav-endscreen-upnext-title",yD:"{{title}}"},{J:"div",L:"ytp-autonav-endscreen-upnext-author",
yD:"{{author}}"},{J:"div",L:"ytp-autonav-view-and-date",yD:"{{views_and_publish_time}}"},{J:"div",L:"ytp-autonav-author-and-view",yD:"{{author_and_views}}"}]}]}]});g.R(this,this.D);this.D.oA(this.container.element);F||this.Y(this.D.pJ("ytp-autonav-endscreen-link-container"),"click",this.tA);this.X.createClientVe(this.container.element,this,115127);this.X.createClientVe(this.D.pJ("ytp-autonav-endscreen-link-container"),this,115128);this.closeButton=new g.Q({J:"button",L:"ytp-autonav-endscreen-upnext-header-close-button",
S:{"aria-label":"Cancel autoplay"}});g.R(this,this.closeButton);b.C("web_post_play_autonav_embiggening")&&(this.closeButton.listen("click",this.NT,this),this.X.createClientVe(this.closeButton.element,this,115129),this.D.pJ("ytp-autonav-endscreen-topbar-container").appendChild(this.closeButton.element));this.overlay=new g.Q({J:"div",L:"ytp-autonav-overlay"});g.R(this,this.overlay);this.overlay.oA(this.container.element);this.Z=new g.Q({J:"div",L:"ytp-autonav-endscreen-button-container"});g.R(this,
this.Z);this.Z.oA(this.container.element);this.cancelButton=new g.Q({J:"button",aA:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],S:{"aria-label":"Cancel autoplay"},yD:"Cancel"});g.R(this,this.cancelButton);this.cancelButton.oA(this.Z.element);this.cancelButton.listen("click",this.NT,this);this.X.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.Q({J:"a",aA:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button","ytp-autonav-endscreen-upnext-button-rounded"],S:{href:"{{url}}",role:"button","aria-label":"Play next video"},yD:"Play Now"});g.R(this,this.playButton);this.playButton.oA(this.Z.element);this.playButton.listen("click",this.tA,this);this.X.createServerVe(this.playButton.element,this.playButton,!0);(C=this.X.getVideoData())&&Np5(this,C);this.B=new g.D5(()=>{Vv(this)},500);
g.R(this,this.B);this.AA();this.Y(b,"autonavvisibility",this.AA)}W(b){this.suggestion!==b&&(this.suggestion=b,g.vv(this.D,b),this.playButton.updateValue("url",this.suggestion.mH()),gO(this))}O(){return this.K>0}G(){this.O()||(this.K=Date.now(),Vv(this),F33(this.X,Y8(this)),g.kk(this.X.getRootNode(),"countdown-running",this.O()))}N(){this.A();Vv(this);var b=this.D.pJ("ytp-autonav-endscreen-upnext-header");b&&g.nC(b,"Up next")}A(){this.O()&&(this.B.stop(),this.K=0)}select(b=!1){this.X.nextVideo(!1,
b);this.A()}tA(b){g.ZY(b,this.X)&&(b.currentTarget===this.playButton.element?this.X.logClick(this.playButton.element):b.currentTarget===this.D.pJ("ytp-autonav-endscreen-link-container")&&(b=this.D.pJ("ytp-autonav-endscreen-link-container"),this.X.logVisibility(b,!0),this.X.logClick(b)),this.DQ?(g.hT(this.X,"innertubeCommand",this.DQ),this.A()):this.select())}NT(){this.X.logClick(this.cancelButton.element);g.fB(this.X,!0);this.cancelCommand&&g.hT(this.X,"innertubeCommand",this.cancelCommand)}onVideoDataChange(b,
C){Np5(this,C);this.cancelCommand=C.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.cancelButton?.buttonRenderer?.command}AA(){var b=this.X.S3();this.pX!==b&&this.fX(b);gO(this);this.X.logVisibility(this.container.element,b);this.X.logVisibility(this.cancelButton.element,b);this.X.logVisibility(this.D.pJ("ytp-autonav-endscreen-link-container"),b);this.X.logVisibility(this.playButton.element,b)}ue(b){return b.width<400||b.height<459}};var qE=class extends g.Q{constructor(b,C){super({J:"div",aA:["html5-endscreen","ytp-player-content",C||"base-endscreen"]});this.created=!1;this.player=b}create(){this.created=!0}destroy(){this.created=!1}B(){return!1}S3(){return!1}DQ(){return!1}};var L3s=class extends g.Q{constructor(b){super({J:"div",aA:["ytp-upnext","ytp-player-content"],S:{"aria-label":"{{aria_label}}"},j:[{J:"div",L:"ytp-cued-thumbnail-overlay-image",S:{style:"{{background}}"}},{J:"span",L:"ytp-upnext-top",j:[{J:"span",L:"ytp-upnext-header",yD:"Up Next"},{J:"span",L:"ytp-upnext-title",yD:"{{title}}"},{J:"span",L:"ytp-upnext-author",yD:"{{author}}"}]},{J:"a",L:"ytp-upnext-autoplay-icon",S:{role:"button",href:"{{url}}","aria-label":"Play next video"},j:[{J:"svg",S:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},j:[{J:"circle",L:"ytp-svg-autoplay-circle",S:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{J:"circle",L:"ytp-svg-autoplay-ring",S:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{J:"path",L:"ytp-svg-fill",S:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{J:"span",L:"ytp-upnext-bottom",j:[{J:"span",L:"ytp-upnext-cancel"},
{J:"span",L:"ytp-upnext-paused",yD:"Autoplay is paused"}]}]});this.api=b;this.cancelButton=null;this.ej=this.pJ("ytp-svg-autoplay-ring");this.B=this.notification=this.D=this.suggestion=null;this.DQ=new g.D5(this.Z,5E3,this);this.K=0;var C=this.pJ("ytp-upnext-cancel");this.cancelButton=new g.Q({J:"button",aA:["ytp-upnext-cancel-button","ytp-button"],S:{tabindex:"0","aria-label":"Cancel autoplay"},yD:"Cancel"});g.R(this,this.cancelButton);this.cancelButton.listen("click",this.NT,this);this.cancelButton.oA(C);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.R(this,this.DQ);this.api.createClientVe(this.element,this,18788);C=this.pJ("ytp-upnext-autoplay-icon");this.Y(C,"click",this.tA);this.api.createClientVe(C,this,115130);this.AA();this.Y(b,"autonavvisibility",this.AA);this.Y(b,"mdxnowautoplaying",this.XS);this.Y(b,"mdxautoplaycanceled",this.ZQ);g.kk(this.element,"ytp-upnext-mobile",this.api.U().A)}Z(){this.notification&&(this.DQ.stop(),this.nF(this.B),this.B=null,this.notification.close(),
this.notification=null)}W(b){this.suggestion=b;g.vv(this,b,"hqdefault.jpg")}AA(){this.fX(this.api.S3());this.api.logVisibility(this.element,this.api.S3());this.api.logVisibility(this.pJ("ytp-upnext-autoplay-icon"),this.api.S3());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.S3())}KJ(){window.focus();this.Z()}G(b){this.O()||(g.$9("a11y-announce",`Up Next ${this.suggestion.title}`),this.K=(0,g.u)(),this.D=new g.D5(()=>{Kk(this,b)},25),Kk(this,b),F33(this.api,hSl(this,
b)));
g.$k(this.element,"ytp-upnext-autoplay-paused")}hide(){super.hide()}O(){return!!this.D}isCasting(){return this.api.getPresentingPlayerType()===3}N(){this.A();this.K=(0,g.u)();Kk(this);g.jQ(this.element,"ytp-upnext-autoplay-paused")}A(){this.O()&&(this.D.dispose(),this.D=null)}select(b=!1){if(this.api.U().C("autonav_notifications")&&b&&window.Notification&&typeof document.hasFocus==="function"){let C=Notification.permission;C==="default"?Notification.requestPermission():C!=="granted"||document.hasFocus()||
(this.Z(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Yv()}),this.B=this.Y(this.notification,"click",this.KJ),this.DQ.start())}this.A();this.api.nextVideo(!1,b)}tA(b){!g.YO(this.cancelButton.element,b.target)&&g.ZY(b,this.api)&&(this.api.S3()&&this.api.logClick(this.pJ("ytp-upnext-autoplay-icon")),this.select())}NT(){this.api.S3()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.fB(this.api,!0)}XS(b){this.isCasting();this.show();
this.G(b)}ZQ(){this.isCasting();this.A();this.hide()}GD(){this.A();this.Z();super.GD()}};var YQ5=class extends qE{constructor(b){super(b,"videowall-endscreen");this.X=b;this.stills=[];this.N=this.videoData=null;this.G=this.W=!1;this.AA=null;g.jQ(this.element,"modern-videowall-endscreen");this.D=new g.d7(this);g.R(this,this.D);this.Z=new g.D5(()=>{g.jQ(this.element,"ytp-show-tiles")},0);
g.R(this,this.Z);this.table=new g.XK({J:"div",L:"ytp-modern-endscreen-content"});g.R(this,this.table);this.table.oA(this.element);b.getVideoData().hf?this.O=new PN(b):this.O=new L3s(b);g.R(this,this.O);g.O4(this.player,this.O.element,4);b.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var b=this.player.getVideoData();b&&(this.videoData=b);this.A();this.D.Y(this.player,"appresize",this.A);this.D.Y(this.player,"onVideoAreaChange",this.A);this.D.Y(this.player,"videodatachange",
this.onVideoDataChange);this.D.Y(this.player,"autonavchange",this.K);this.D.Y(this.player,"onAutonavCancelled",this.NT);b=this.videoData.autonavState;b!==this.AA&&this.K(b,!1);this.D.Y(this.element,"transitionend",this.tA)}destroy(){this.D.D();g.Mo(this.stills);this.stills=[];super.destroy();g.$k(this.element,"ytp-show-tiles");this.Z.stop();this.AA=this.videoData.autonavState}B(){return this.videoData?.CF||this.videoData.autonavState!==1}show(){var b=this.pX;super.show();g.$k(this.element,"ytp-show-tiles");
this.player.U().A?g.pn(this.Z):this.Z.start();(this.G||this.N&&this.N!==this.videoData.clientPlaybackNonce)&&g.fB(this.player,!1);Db(this)?(ME(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||zSB(this.player.CU())&&this.player.C("web_player_pip_logging_fix")?this.O.select(!0):this.O.G():this.videoData.autonavState===3&&this.O.N()):(g.fB(this.player,!0),ME(this));b!==this.pX&&this.player.logVisibility(this.element,!0)}hide(){var b=this.pX;super.hide();this.O.N();ME(this);
b!==this.pX&&this.player.logVisibility(this.element,!1)}tA(b){b.target===this.element&&this.A()}A(){var b=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.W()];if(b.length){var C=this.X.D3(!0,this.X.isFullscreen()),F=Math.floor((C.width-64+16)/(g.f_(C.width*.27,250,450)+16));C=Math.min(3,Math.floor((C.height-64)/((C.width-64-(F-1)*16)/F*.5625+70)));g.lN(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.jQ(this.element,`ytp-modern-endscreen-limit-rows-${C}`);g.kk(this.element,"ytp-modern-endscreen-single-item",F===1);g.kk(this.element,"ytp-modern-endscreen-row-0",C===0);F=this.table.element;F.ariaLive="polite";this.O.W(this.videoData.W());this.O instanceof PN&&gO(this.O);g.kk(this.element,"ytp-endscreen-takeover",Db(this));ME(this);C=0;F.ariaBusy="true";var z=b.length;for(let N=0;N<z;N++){let h=N%z,H=this.stills[N];H||(H=new g.D1b(this.player),this.stills[N]=H,F.appendChild(H.element));g.h_j(H,
b[h]);C++}this.stills.length=C}}onVideoDataChange(){var b=this.player.getVideoData({playerType:1});this.videoData!==b&&(b?.W()?(this.videoData=b,this.A()):this.player.FS("missg",{vid:b?.videoId||"",cpn:b?.clientPlaybackNonce||""}))}DQ(){return this.O.O()}K(b,C=!1){var F=this.videoData?.CF;if(b===1){if(!F||C)this.G=!1,this.N=this.videoData.clientPlaybackNonce;this.O.A();this.pX&&this.A()}else this.G=!0,this.pX&&Db(this)&&(b===2?this.O.G():b===3&&this.O.N())}NT(b){if(b){for(b=0;b<this.stills.length;b++)this.X.logVisibility(this.stills[b].element,
!0);this.K(1,!0)}else this.N=null,this.G=!1;this.A()}S3(){return this.pX&&Db(this)}};var nVU=class extends g.Q{constructor(b){var C=b.U(),F=g.ej||g.c1?{style:"will-change: opacity"}:void 0,z=C.N,N=["ytp-videowall-still"];C.A&&N.push("ytp-videowall-show-text");super({J:"a",aA:N,S:{href:"{{url}}",target:z?C.AA:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},j:[{J:"div",L:"ytp-videowall-still-image",S:{style:"{{background}}"}},{J:"span",L:"ytp-videowall-still-info",S:{"aria-hidden":"true"},j:[{J:"span",L:"ytp-videowall-still-info-bg",
j:[{J:"span",L:"ytp-videowall-still-info-content",S:F,j:[{J:"span",L:"ytp-videowall-still-info-title",yD:"{{title}}"},{J:"span",L:"ytp-videowall-still-info-author",yD:"{{author_and_views}}"},{J:"span",L:"ytp-videowall-still-info-live",yD:"Live"},{J:"span",L:"ytp-videowall-still-info-duration",yD:"{{duration}}"}]}]}]},{J:"span",aA:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],S:{"aria-hidden":"true"},j:[{J:"span",L:"ytp-videowall-still-listlabel-icon"},"Playlist",{J:"span",
L:"ytp-videowall-still-listlabel-length",j:[" (",{J:"span",yD:"{{playlist_length}}"},")"]}]},{J:"span",aA:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],S:{"aria-hidden":"true"},j:[{J:"span",L:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{J:"span",L:"ytp-videowall-still-listlabel-length",yD:" (50+)"}]}]});this.suggestion=null;this.D=z;this.api=b;this.O=new g.d7(this);g.R(this,this.O);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.O.Y(b,"videodatachange",
this.onVideoDataChange);b.createServerVe(this.element,this);this.onVideoDataChange()}select(){this.api.uJ(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Eg||void 0)&&this.api.logClick(this.element)}onClick(b){if(g.Sd(this.api.U())&&this.api.C("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);let C=this.suggestion.mH(),F={};g.i3(this.api,F);C=g.TR(C,F);g.w3(C,this.api,b)}else g.ZY(b,this.api,
this.D,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(b){switch(b.keyCode){case 13:case 32:b.defaultPrevented||(this.select(),b.preventDefault())}}onVideoDataChange(){var b=this.api.getVideoData(),C=this.api.U();this.D=b.JP?!1:C.N}};var VUn=class extends qE{constructor(b){super(b,"videowall-endscreen");this.X=b;this.N=0;this.stills=[];this.G=this.videoData=null;this.Z=this.AA=!1;this.NT=null;this.A=new g.d7(this);g.R(this,this.A);this.K=new g.D5(()=>{g.jQ(this.element,"ytp-show-tiles")},0);
g.R(this,this.K);var C=new g.Q({J:"button",aA:["ytp-button","ytp-endscreen-previous"],S:{"aria-label":"Previous"},j:[g.Rc()]});g.R(this,C);C.oA(this.element);C.listen("click",this.XS,this);this.table=new g.XK({J:"div",L:"ytp-endscreen-content"});g.R(this,this.table);this.table.oA(this.element);C=new g.Q({J:"button",aA:["ytp-button","ytp-endscreen-next"],S:{"aria-label":"Next"},j:[g.ve()]});g.R(this,C);C.oA(this.element);C.listen("click",this.ej,this);b.getVideoData().hf?this.O=new PN(b):this.O=new L3s(b);
g.R(this,this.O);g.O4(this.player,this.O.element,4);b.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var b=this.player.getVideoData();b&&(this.videoData=b);this.D();this.A.Y(this.player,"appresize",this.D);this.A.Y(this.player,"onVideoAreaChange",this.D);this.A.Y(this.player,"videodatachange",this.onVideoDataChange);this.A.Y(this.player,"autonavchange",this.W);this.A.Y(this.player,"onAutonavCancelled",this.tA);b=this.videoData.autonavState;b!==this.NT&&this.W(b,!1);this.A.Y(this.element,
"transitionend",this.ZQ)}destroy(){this.A.D();g.Mo(this.stills);this.stills=[];super.destroy();g.$k(this.element,"ytp-show-tiles");this.K.stop();this.NT=this.videoData.autonavState}B(){return this.videoData?.CF||this.videoData?.autonavState!==1}show(){var b=this.pX;super.show();g.$k(this.element,"ytp-show-tiles");this.player.U().A?g.pn(this.K):this.K.start();(this.Z||this.G&&this.G!==this.videoData.clientPlaybackNonce)&&g.fB(this.player,!1);pk(this)?(dO(this),this.videoData.autonavState===2?this.player.getVisibilityState()===
3||zSB(this.player.CU())&&this.player.C("web_player_pip_logging_fix")?this.O.select(!0):this.O.G():this.videoData.autonavState===3&&this.O.N()):(g.fB(this.player,!0),dO(this));b!==this.pX&&this.player.logVisibility(this.element,!0)}hide(){var b=this.pX;super.hide();this.O.N();dO(this);b!==this.pX&&this.player.logVisibility(this.element,!1)}ZQ(b){b.target===this.element&&this.D()}D(){var b=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.W()];if(b.length){g.jQ(this.element,
"ytp-endscreen-paginate");var C=this.X.D3(!0,this.X.isFullscreen()),F=g.VE(this.X);F&&(F=F.Uz()?48:32,C.width-=F*2);var z=C.width/C.height,N=96/54,h=F=2,H=Math.max(C.width/96,2),c=Math.max(C.height/54,2),r=b.length;var L=r*4;for(L-=4;L>0&&(F<H||h<c);){var K=F/2,D=h/2,P=F<=H-2&&L>=D*4,M=h<=c-2&&L>=K*4;if((K+1)/D*N/z>z/(K/(D+1)*N)&&M)L-=K*4,h+=2;else if(P)L-=D*4,F+=2;else if(M)L-=K*4,h+=2;else break}N=!1;L>=12&&r*4-L<=6&&(h>=4||F>=4)&&(N=!0);L=F*96;H=h*54;z=L/H<z?C.height/H:C.width/L;z=Math.min(z,2);
L=Math.floor(Math.min(C.width,L*z));H=Math.floor(Math.min(C.height,H*z));C=this.table.element;C.ariaLive="polite";g.E9(C,L,H);g.xO(C,{marginLeft:`${L/-2}px`,marginTop:`${H/-2}px`});this.O.W(this.videoData.W());this.O instanceof PN&&gO(this.O);g.kk(this.element,"ytp-endscreen-takeover",pk(this));dO(this);L+=4;H+=4;z=0;C.ariaBusy="true";for(c=0;c<F;c++)for(K=0;K<h;K++)if(P=z,M=0,N&&c>=F-2&&K>=h-2?M=1:K%2===0&&c%2===0&&(K<2&&c<2?K===0&&c===0&&(M=2):M=2),P=g.lv(P+this.N,r),M!==0){D=this.stills[z];D||
(D=new nVU(this.player),this.stills[z]=D,C.appendChild(D.element));var f=Math.floor(H*K/h);let U=Math.floor(L*c/F),W=Math.floor(H*(K+M)/h)-f-4,A=Math.floor(L*(c+M)/F)-U-4;g.J8(D.element,U,f);g.E9(D.element,A,W);g.xO(D.element,"transitionDelay",(K+c)/20+"s");g.kk(D.element,"ytp-videowall-still-mini",M===1);g.kk(D.element,"ytp-videowall-still-large",M>2);M=Math.max(A,W);g.kk(D.element,"ytp-videowall-still-round-large",M>=256);g.kk(D.element,"ytp-videowall-still-round-medium",M>96&&M<256);g.kk(D.element,
"ytp-videowall-still-round-small",M<=96);P=b[P];D.suggestion!==P&&(D.suggestion=P,M=D.api.U(),f=g.B4(D.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.vv(D,P,f),g.Sd(M)&&!D.api.C("web_player_log_click_before_generating_ve_conversion_params")&&(M=P.mH(),f={},g.r3(D.api,"addEmbedsConversionTrackingParams",[f]),M=g.TR(M,f),D.updateValue("url",M)),(P=(P=P.sessionData)&&P.itct)&&D.api.setTrackingParams(D.element,P));z++}C.ariaBusy="false";g.kk(this.element,"ytp-endscreen-paginate",
z<r);for(b=this.stills.length-1;b>=z;b--)F=this.stills[b],g.LC(F.element),g.Ds(F);this.stills.length=z}}onVideoDataChange(){var b=this.player.getVideoData({playerType:1});this.videoData!==b&&(b?.W()?(this.N=0,this.videoData=b,this.D()):this.player.FS("missg",{vid:b?.videoId||"",cpn:b?.clientPlaybackNonce||""}))}ej(){this.N+=this.stills.length;this.D()}XS(){this.N-=this.stills.length;this.D()}DQ(){return this.O.O()}W(b,C=!1){var F=this.videoData?.CF;if(b===1){if(!F||C)this.Z=!1,this.G=this.videoData.clientPlaybackNonce;
this.O.A();this.pX&&this.D()}else this.Z=!0,this.pX&&pk(this)&&(b===2?this.O.G():b===3&&this.O.N())}tA(b){if(b){for(b=0;b<this.stills.length;b++)this.X.logVisibility(this.stills[b].element,!0);this.W(1,!0)}else this.G=null,this.Z=!1;this.D()}S3(){return this.pX&&pk(this)}};var gVT=class extends g.Q{constructor(b){super({J:"button",aA:["ytp-watch-on-youtube-button","ytp-button"],yD:"{{content}}"});this.X=b;this.buttonType=this.buttonType=1;this.O();this.buttonType===2&&g.jQ(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.O);this.fX(!0)}O(){switch(this.buttonType){case 1:var b="Watch again on YouTube";var C=156915;break;case 2:b="Continue watching on YouTube";C=156942;break;default:b="Continue watching on YouTube",
C=156942}this.update({content:b});this.X.hasVe(this.element)&&this.X.destroyVe(this.element);this.X.createClientVe(this.element,this,C)}onClick(b){this.X.C("web_player_log_click_before_generating_ve_conversion_params")&&this.X.logClick(this.element);g.w3(this.getVideoUrl(),this.X,b);this.X.C("web_player_log_click_before_generating_ve_conversion_params")||this.X.logClick(this.element)}getVideoUrl(){var b=!0;switch(this.buttonType){case 1:b=!0;break;case 2:b=!1}b=this.X.getVideoUrl(b,!1,!1,!0);var C=
this.X.U();if(g.Sd(C)){let F={};g.Sd(C)&&g.r3(this.X,"addEmbedsConversionTrackingParams",[F]);b=g.TR(b,F)}return b}logVisibility(){this.X.logVisibility(this.element,this.pX&&this.lB)}show(){super.show();this.logVisibility()}hide(){super.hide();this.logVisibility()}X1(b){super.X1(b);this.logVisibility()}};var K3V=class extends qE{constructor(b){super(b,"watch-again-on-youtube-endscreen");this.watchButton=new gVT(b);g.R(this,this.watchButton);this.watchButton.oA(this.element);g.V1Y(b)&&(this.O=new g.FD3(b),g.R(this,this.O),this.D=new g.Q({J:"div",aA:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],S:{tabIndex:"-1"},j:[this.O]}),g.R(this,this.D),this.O.oA(this.D.element),this.D.oA(this.element));b.createClientVe(this.element,this,156914);this.hide()}hasSuggestions(){return this.O?.hasSuggestions()}show(){if(this.player.getPlayerState()!==
3){super.show();let C=this.D;if(C){var b=this.O.hasSuggestions();g.kk(this.element,"ytp-shorts-branded-ui",b);b?C.show():C.hide()}g.VE(this.player)?.qe(!0);this.player.logVisibility(this.element,!0);this.watchButton.X1(!0)}}hide(){super.hide();g.VE(this.player)?.qe(!1);this.player.logVisibility(this.element,!1);this.watchButton.X1(!1)}};g.QR("endscreen",class extends g.Ro{constructor(b){super(b);this.endScreen=null;this.O=this.D=!1;this.listeners=new g.d7(this);g.R(this,this.listeners);var C=b.U();b.isEmbedsShortsMode()?this.endScreen=new K3V(b):HS7(b)?(this.D=!0,c2V(this),C.C("delhi_modern_endscreen")?this.endScreen=new YQ5(b):this.endScreen=new VUn(b)):this.endScreen=new qE(b);g.R(this,this.endScreen);g.O4(b,this.endScreen.element,4);r2s(this);this.listeners.Y(b,"videodatachange",this.onVideoDataChange,this);this.listeners.Y(b,
g.mw("endscreen"),F=>{this.onCueRangeEnter(F)});
this.listeners.Y(b,g.S7("endscreen"),F=>{this.onCueRangeExit(F)})}gN(){var b=this.player.getVideoData(),C=b.mutedAutoplay&&(b.limitedPlaybackDurationInSeconds>0||b.endSeconds>0||b.mutedAutoplayDurationMode!==2);
if(this.player.isEmbedsShortsMode()&&!C)return!0;var F=!(!b?.W()&&!b?.suggestions?.length);F=!HS7(this.player)||F;var z=b.N8,N=this.player.qO();return(F||!!b?.CF)&&!z&&!N&&!C}S3(){return this.endScreen.S3()}xZ(){return this.S3()?this.endScreen.DQ():!1}GD(){this.player.gw("endscreen");super.GD()}load(){{let F=this.player.getVideoData(),z=F.transitionEndpointAtEndOfStream;if(z&&z.videoId){var b=this.player.gR().hM.get("heartbeat");var C=F.W();!C||z.videoId!==C.videoId||F.It?(this.player.uJ(z.videoId,
void 0,void 0,!0,!0,z),b&&b.tT("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),b=!0):b=!1}else b=!1}b||(super.load(),this.endScreen.show())}unload(){super.unload();this.endScreen.hide();this.endScreen.destroy()}onCueRangeEnter(b){this.gN()&&(this.endScreen.created||this.endScreen.create(),b.getId()==="load"&&this.load())}onCueRangeExit(b){b.getId()==="load"&&this.loaded&&this.unload()}onVideoDataChange(){r2s(this);this.D&&c2V(this)&&
(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.endScreen=new VUn(this.player),g.R(this,this.endScreen),g.O4(this.player,this.endScreen.element,4))}});})(_yt_player);
